//go:build windows

package main

import (
	"encoding/base64"
	"encoding/binary"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"sync"
	"syscall"
	"unicode/utf16"
	"unsafe"
)

var (
	user32   = syscall.NewLazyDLL("user32.dll")
	kernel32 = syscall.NewLazyDLL("kernel32.dll")
	ole32    = syscall.NewLazyDLL("ole32.dll")
	gdi32    = syscall.NewLazyDLL("gdi32.dll")
	uxtheme  = syscall.NewLazyDLL("uxtheme.dll")
	dwmapi   = syscall.NewLazyDLL("dwmapi.dll")
	shell32  = syscall.NewLazyDLL("shell32.dll")
	advapi32 = syscall.NewLazyDLL("advapi32.dll")

	procRegisterClassExW              = user32.NewProc("RegisterClassExW")
	procCreateWindowExW               = user32.NewProc("CreateWindowExW")
	procDefWindowProcW                = user32.NewProc("DefWindowProcW")
	procGetMessageW                   = user32.NewProc("GetMessageW")
	procTranslateMessage              = user32.NewProc("TranslateMessage")
	procDispatchMessageW              = user32.NewProc("DispatchMessageW")
	procPostQuitMessage               = user32.NewProc("PostQuitMessage")
	procMoveWindow                    = user32.NewProc("MoveWindow")
	procSendMessageW                  = user32.NewProc("SendMessageW")
	procPostMessageW                  = user32.NewProc("PostMessageW")
	procSetWindowTextW                = user32.NewProc("SetWindowTextW")
	procGetWindowTextLengthW          = user32.NewProc("GetWindowTextLengthW")
	procGetWindowTextW                = user32.NewProc("GetWindowTextW")
	procGetClientRect                 = user32.NewProc("GetClientRect")
	procSetFocus                      = user32.NewProc("SetFocus")
	procMessageBoxW                   = user32.NewProc("MessageBoxW")
	procLoadCursorW                   = user32.NewProc("LoadCursorW")
	procLoadIconW                     = user32.NewProc("LoadIconW")
	procBeginPaint                    = user32.NewProc("BeginPaint")
	procEndPaint                      = user32.NewProc("EndPaint")
	procFillRect                      = user32.NewProc("FillRect")
	procFrameRect                     = user32.NewProc("FrameRect")
	procDrawTextW                     = user32.NewProc("DrawTextW")
	procDrawIconEx                    = user32.NewProc("DrawIconEx")
	procInvalidateRect                = user32.NewProc("InvalidateRect")
	procUpdateWindow                  = user32.NewProc("UpdateWindow")
	procRedrawWindow                  = user32.NewProc("RedrawWindow")
	procEnableWindow                  = user32.NewProc("EnableWindow")
	procShowWindow                    = user32.NewProc("ShowWindow")
	procGetDpiForWindow               = user32.NewProc("GetDpiForWindow")
	procSetProcessDpiAwarenessContext = user32.NewProc("SetProcessDpiAwarenessContext")

	procGetModuleHandleW = kernel32.NewProc("GetModuleHandleW")
	procCreateFontW      = gdi32.NewProc("CreateFontW")
	procCreateSolidBrush = gdi32.NewProc("CreateSolidBrush")
	procCreatePen        = gdi32.NewProc("CreatePen")
	procDeleteObject     = gdi32.NewProc("DeleteObject")
	procSelectObject     = gdi32.NewProc("SelectObject")
	procRoundRect        = gdi32.NewProc("RoundRect")
	procSetTextColor     = gdi32.NewProc("SetTextColor")
	procSetBkColor       = gdi32.NewProc("SetBkColor")
	procSetBkMode        = gdi32.NewProc("SetBkMode")
	procStretchDIBits    = gdi32.NewProc("StretchDIBits")

	procCoInitializeEx        = ole32.NewProc("CoInitializeEx")
	procCoUninitialize        = ole32.NewProc("CoUninitialize")
	procCoCreateInstance      = ole32.NewProc("CoCreateInstance")
	procCoTaskMemFree         = ole32.NewProc("CoTaskMemFree")
	procSetWindowTheme        = uxtheme.NewProc("SetWindowTheme")
	procDwmSetWindowAttribute = dwmapi.NewProc("DwmSetWindowAttribute")
	procDragAcceptFiles       = shell32.NewProc("DragAcceptFiles")
	procDragQueryFileW        = shell32.NewProc("DragQueryFileW")
	procDragFinish            = shell32.NewProc("DragFinish")
	procShellExecuteW         = shell32.NewProc("ShellExecuteW")
	procSHChangeNotify        = shell32.NewProc("SHChangeNotify")
	procRegCreateKeyExW       = advapi32.NewProc("RegCreateKeyExW")
	procRegSetValueExW        = advapi32.NewProc("RegSetValueExW")
	procRegCloseKey           = advapi32.NewProc("RegCloseKey")
	procRegDeleteTreeW        = advapi32.NewProc("RegDeleteTreeW")
)

const (
	WS_OVERLAPPEDWINDOW  = 0x00CF0000
	WS_VISIBLE           = 0x10000000
	WS_CHILD             = 0x40000000
	WS_TABSTOP           = 0x00010000
	WS_VSCROLL           = 0x00200000
	WS_HSCROLL           = 0x00100000
	WS_BORDER            = 0x00800000
	WS_CLIPCHILDREN      = 0x02000000
	WS_EX_CLIENTEDGE     = 0x00000200
	ES_MULTILINE         = 0x0004
	ES_AUTOVSCROLL       = 0x0040
	ES_AUTOHSCROLL       = 0x0080
	ES_WANTRETURN        = 0x1000
	ES_READONLY          = 0x0800
	ES_NOHIDESEL         = 0x0100
	BS_OWNERDRAW         = 0x000B
	BS_AUTOCHECKBOX      = 0x0003
	CBS_DROPDOWNLIST     = 0x0003
	CBS_HASSTRINGS       = 0x0200
	CBS_OWNERDRAWFIXED   = 0x0010
	CBS_NOINTEGRALHEIGHT = 0x0400
	SS_LEFT              = 0x0000
	LBS_NOTIFY           = 0x0001
	LBS_NOINTEGRALHEIGHT = 0x0100

	WM_DESTROY           = 0x0002
	WM_SIZE              = 0x0005
	WM_PAINT             = 0x000F
	WM_ERASEBKGND        = 0x0014
	WM_GETMINMAXINFO     = 0x0024
	WM_COMMAND           = 0x0111
	WM_DRAWITEM          = 0x002B
	WM_MEASUREITEM       = 0x002C
	WM_SETFONT           = 0x0030
	WM_CTLCOLORMSGBOX    = 0x0132
	WM_CTLCOLOREDIT      = 0x0133
	WM_CTLCOLORLISTBOX   = 0x0134
	WM_CTLCOLORBTN       = 0x0135
	WM_CTLCOLORDLG       = 0x0136
	WM_CTLCOLORSCROLLBAR = 0x0137
	WM_CTLCOLORSTATIC    = 0x0138
	WM_DROPFILES         = 0x0233
	WM_PASTE             = 0x0302
	WM_COPY              = 0x0301
	WM_SETREDRAW         = 0x000B
	WM_APP_ANALYSIS_DONE = 0x8001

	EM_SETSEL          = 0x00B1
	EM_SETLIMITTEXT    = 0x00C5
	EM_SETMARGINS      = 0x00D3
	EC_LEFTMARGIN      = 0x0001
	EC_RIGHTMARGIN     = 0x0002
	CB_ADDSTRING       = 0x0143
	CB_GETCOUNT        = 0x0146
	CB_GETLBTEXT       = 0x0148
	CB_GETLBTEXTLEN    = 0x0149
	CB_GETCURSEL       = 0x0147
	CB_SETCURSEL       = 0x014E
	CB_SETITEMHEIGHT   = 0x0153
	CB_SETMINVISIBLE   = 0x1701
	CB_SHOWDROPDOWN    = 0x014F
	CB_SETDROPPEDWIDTH = 0x0160
	LB_ADDSTRING       = 0x0180
	LB_GETCURSEL       = 0x0188
	LB_SETCURSEL       = 0x0186
	LB_GETCOUNT        = 0x018B
	BM_GETCHECK        = 0x00F0
	BST_CHECKED        = 1
	CW_USEDEFAULT      = 0x80000000
	SW_HIDE            = 0
	SW_SHOW            = 5
	SW_MAXIMIZE        = 3

	ODT_BUTTON       = 4
	ODT_COMBOBOX     = 3
	ODS_SELECTED     = 0x0001
	ODS_FOCUS        = 0x0010
	ODS_COMBOBOXEDIT = 0x1000
	DT_LEFT          = 0x0000
	DT_CENTER        = 0x0001
	DT_VCENTER       = 0x0004
	DT_BOTTOM        = 0x0008
	DT_SINGLELINE    = 0x0020
	DT_END_ELLIPSIS  = 0x8000
	TRANSPARENT      = 1
	OPAQUE           = 2
	PS_SOLID         = 0
	DI_NORMAL        = 0x0003

	RDW_INVALIDATE = 0x0001
	RDW_ERASE      = 0x0004
	RDW_UPDATENOW  = 0x0100
	RDW_FRAME      = 0x0400

	HKEY_CURRENT_USER  = 0x80000001
	KEY_WRITE          = 0x20006
	REG_SZ             = 1
	SHCNE_ASSOCCHANGED = 0x08000000

	ID_TITLE           = 90
	ID_TAGLINE         = 91
	ID_EDIT_INPUT      = 101
	ID_PASTE           = 102
	ID_OPEN            = 103
	ID_CLEAR           = 104
	ID_QUICK_AZ        = 105
	ID_QUICK_REP       = 106
	ID_QUICK_KUNTA     = 107
	ID_QUICK_VOW       = 108
	ID_QUICK_CONS      = 109
	ID_COMBO           = 110
	ID_PARAM           = 111
	ID_CASE            = 112
	ID_RUN             = 113
	ID_HINT            = 114
	ID_OUTPUT          = 115
	ID_COPY            = 116
	ID_STATUS          = 117
	ID_LABEL_OPERATION = 118
	ID_LABEL_PARAM     = 119
	ID_FOOTER          = 120
	ID_OPLIST          = 121
)

const repoURL = "https://github.com/ShiduLab/Kunta"

type POINT struct{ X, Y int32 }
type MSG struct {
	Hwnd           uintptr
	Message        uint32
	WParam, LParam uintptr
	Time           uint32
	Pt             POINT
}
type RECT struct{ Left, Top, Right, Bottom int32 }
type WNDCLASSEX struct {
	CbSize                                   uint32
	Style                                    uint32
	LpfnWndProc                              uintptr
	CbClsExtra, CbWndExtra                   int32
	HInstance, HIcon, HCursor, HbrBackground uintptr
	LpszMenuName, LpszClassName              *uint16
	HIconSm                                  uintptr
}
type GUID struct {
	Data1 uint32
	Data2 uint16
	Data3 uint16
	Data4 [8]byte
}
type COMDLG_FILTERSPEC struct {
	Name *uint16
	Spec *uint16
}
type BITMAPINFOHEADER struct {
	Size          uint32
	Width         int32
	Height        int32
	Planes        uint16
	BitCount      uint16
	Compression   uint32
	SizeImage     uint32
	XPelsPerMeter int32
	YPelsPerMeter int32
	ClrUsed       uint32
	ClrImportant  uint32
}
type BITMAPINFO struct {
	Header BITMAPINFOHEADER
	Colors [1]uint32
}
type PAINTSTRUCT struct {
	Hdc         uintptr
	FErase      int32
	RcPaint     RECT
	FRestore    int32
	FIncUpdate  int32
	RgbReserved [32]byte
}
type DRAWITEMSTRUCT struct {
	CtlType    uint32
	CtlID      uint32
	ItemID     uint32
	ItemAction uint32
	ItemState  uint32
	HwndItem   uintptr
	HDC        uintptr
	RcItem     RECT
	ItemData   uintptr
}
type MEASUREITEMSTRUCT struct {
	CtlType, CtlID, ItemID, ItemWidth, ItemHeight uint32
	ItemData                                      uintptr
}
type MINMAXINFO struct {
	PtReserved, PtMaxSize, PtMaxPosition, PtMinTrackSize, PtMaxTrackSize POINT
}

func rgb(r, g, b byte) uintptr { return uintptr(r) | uintptr(g)<<8 | uintptr(b)<<16 }

var (
	hwndMain                                                                                   uintptr
	hTitle, hTagline, hInput, hParam, hCombo, hOpList, hCase, hHint, hOutput, hStatus, hFooter uintptr
	appIcon                                                                                    uintptr
	controlsByID                                                                               = map[int]uintptr{}
	panelStatics                                                                               = map[uintptr]bool{}

	fontUI, fontSmall, fontTitle, fontMono, fontBold                   uintptr
	brushBG, brushPanel, brushInput, brushAccent, brushSoft, brushLine uintptr

	colBG        = rgb(16, 20, 15)
	colPanel     = rgb(23, 28, 22)
	colInput     = rgb(18, 24, 18)
	colText      = rgb(238, 242, 235)
	colMuted     = rgb(174, 184, 170)
	colAccent    = rgb(124, 186, 47)
	colAccentInk = rgb(13, 22, 6)
	colSoft      = rgb(32, 42, 29)
	colLine      = rgb(57, 67, 55)

	controlPanel  RECT
	currentDPI    = 96
	busyMu        sync.Mutex
	busy          bool
	resultMu      sync.Mutex
	pendingResult string

	botoloPixels []byte
	botoloWidth  int
	botoloHeight int
	botoloStride int
	selectedOp   = 20
	opListOpen   bool
)

// Botolo originale della PWA, senza riquadri colorati; il fondo coincide con quello della UI.
const botoloBMPBase64 = `Qk02bAAAAAAAADYAAAAoAAAAYAAAAGAAAAABABgAAAAAAABsAADEDgAAxA4AAAAAAAAAAAAADxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEBUREhcTERYSDxQQDxQQEBUREhcTERYSDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQERYSEhcTERYSDxQQDxQQEBUREhcTEBYSDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEBURERYSDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEBUREBURDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQERYSDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQERYSEBYSDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQERYSDxQQDxQQHSIgT1JRf4OCnaCgo6ankpaXaGxqMTY0DxQQDxQQERYSDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQERYSDxQQDxQQPUNBbHNxi5KQpKmppKmpj5WVZmxqKjAuDxQQDxQQERYSDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQERYSDxQQHSEffICAzNDQ7fDw5+np2tzb2dva6Orq8vX11tnbiI2OIiglDxQQEBURDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQERYSDxQQPEI/qa2t5urr8PPz5Ofm293b3N7d6Orq8PP01trbjpKTKS8sDxQQERYSDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEBURDxQQO0A+wMLD8PP0vL69hIN/aGFeXVVSX1dUcmtokY6Lzs/O8vX1vsHCMjk2DxQQERYSDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQERYSDxQQVltY4OTk6+3tsbGvgX95aGRgYFhTYltUcWtljYyIxcXD8PLyy9HRRE1LDxQQERYSDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQERYSDxQQOTw51dfY4OPifHl2TEY/RT43UUhEX1ZTXVRSUUhGUklFYVlUsK+t8fPztbm4GyAdERcTEBURDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEhcTEBURPUI/4eTl2draenZyVk9IUUlBWlJLZV1WY1pUVU1GU0pDXFRNiISB4eLi19zdQEZEDxQQERYSDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEBURERcTq6+u6u3tcW5qSkE7XFRQlZGPwL29z83Ny8nIrauobmhlV05MXlZSxMbE8PPzZ2xqDxQQERYSEhcTERYSEBURDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEBURERYSEhcTERYSDxQQDxQQq66t6u3tenVyVUtGYltWlZOQvb+8zM3NysvKtLKwfXh0XVZOVEtEj42J8PLzsre2FhsXEBUREBURDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQERYSDxQQOT486OzsqKimTURAV1FOsK+t6+zs5ujm5eXl5ebl7e/tycnHYlxZVUxIlpSQ7O/vqKysJywpEBURDxQQDxQQDxQQEBUREhcTERYSEBURDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEBURERYSEhcTEBURDxQQDxQQDxQQDxQQDxMPQEVC4uTkt7e3WVBLW1NPo6Gf6u3r3uHh3d/f3eDf4uTj39/dgX14W1NLZ2Faz9DQ5ujpSE9MDxQQERYSDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEhcTDxQQZ2xr8vX1gH57Rz86dG9s4ePh39/e4eLg4OHg3+Df3t/f4eLfdW9qVExGiYaD7e/w5Obn0tbWq7CwcXZ1P0RDGiEeDxQQDxQQDxQQDxQQDxQQEhcTERYSEBURDxQQDxQQEBURERYSEhcTEBURDxQQDxQQDxQQDxQQGR8cNDk3YWRjkpWVuLy82t7e7/LzpqWkV09JY1xXzc/M4OPi2tzb3N7d3N7c2NvZ4+bkubm1XFRNWlRMtLSy8fT0b3Z1DxQQEhcTDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEhcTERYSg4eG8PPzdnVyRj44fnh15OXk4eHg4+Pj4uPh4eHg5ublzMzKYFlVX1ZQamVfko2Jrqyqz9DP5+rp8vX15+rrxcnKl5uaZm1rO0FAHCEeDxQQDxQQDxQQDxQQDxQQERYSDxQQDxQQDxQQDxQQGR8bOT89ZGlpkZeWwMTF4ubm8PP05+nqz9DQsK+tko2LbWdjYllTWlJOv7685ujm293b3uDf3uDe3N/d4uXjv7+8X1ZPWlJLsrGw8/b2dnx7DxQQEhcTDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQExgUDxQQd3t68/b2hYSBSkE8Zl5a19nX4uLi4eHh4uLh4ODg6OnovLy6ZmFeYFhUV05IT0ZAVEtFYVhTdW5rjYqIrKuq0NHQ6erq8fT05OjpxcrLmqGgbHJyPkNBGyEdDxQQDxQQFBkWPUNBbHJymZ6exMnJ4+fo7/P07O7t2NjXtbSzi4eGcGlmXFRQVEtFUUdBVUtHXFRQX1lWsbCt5+nn3t/d3uHf3uHf3eDe6e3rmpiUV09HZV5ZycvK7O/vWl9eDxQQEhcTDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQERYSDxQQMzg1ubu78fPzq6uqUklHUklFmpmW5+fm39/f4eHi4uHi4uLh5OTj3d7cycnHrqyrj4qJdG1rXlVSUUdFTkRCUEhFW1ZTcGxpjYuKr6+t0NHQ6evq8fT05unqxsnKoKSlkpeWvsHC5+vr8PP05+np0NDPr62rjYmId3JvZFtXVEtFUEZBVEtFXVRQbmdkhoJ/o6Gfvry71tjW3+Lg3uHf4eLg3+Hf3uDe5OflxMPAZl5YW1JLhIB75+rq4+bmgomHDxURERYSDxURDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQERYSDxQQKy8tycvM7fDwmZqYXFhUUkpGTUVDf3t63d3c3+Df4eHh4uPi4+Pi4uPi4+Xi5ufm6erp6Onn3d/dyMjHqqioioWDb2poWVZTTklFSkRBTUdEW1ZUb2tqjYyJsLCu0tTT5uno5Ofmzs/PrK2qjIyHc3FsXldUUUdETkRBUUhEXlZSdW5rioaDqKelxMTD19nY5ejm6evp5+ro4uXj4OLh4eLg4uPh4OLg293b5ujmjoyJUktFXVVOZV5Xm5mW3uHh7O7ug4qJDxQQERYSDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEBUREhgToaWl8fPziomJSUE+SUE9bmhlu7q65ufn5+nn6Oro4+Pj4ODe4uPh5OXj4+Th4OLh3N3e3d7d4OPh5ufm6Ojp5ubm29vaxsfFqqqoj42MdXFwXltXV1NMVVNLV1NNY15acGxobWhjYFdTVFFJUk5GV1NOZGBedW9tjouJq6qnxsjF2Nva4eTi5+ro5unn4uXi3+Hf3+Hf3+Hf3+Lg4ePh4ePh4uTi3+De3N7c4OHf3+Deurm3d3JtWFFKVk5GioeD4OHi6ezsYmlpDxQQEhcSDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEhcTDxQQTFFP7fDxrq+tSkJAU0pHi4aFz87Pv769pqOgo6KetbKx1tbV6Ono4OHf4uLg4+Ti4uPi4ODg39/f3+Hg4eLg4+Tj5+jo6evr6erp3uDdxsbEnZuZbmlkXVlRYlxVXVlSWlJOVU9MWVRQaWVhfn15lpaTsrOxyczK3N/d5unn5uro5Obk3uDe297c3+De4eLg4eLg4eLg4+Ti4+Ti4uPh4OLg4OHf4OLg4OHf3uDe3+Df4uPg6Onp4eHhj4yJXVZPVk5HmJeU6evrxsrMIiglDxQQEBURDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQERYSDxQQkZSV7O/vbGloSkE+Z2Nej4yJZV9bT0lDTEI9TkRAVUtJZF5bqKel6Oro5OXj4uPh5OTj5ujm6+zq6uzp4ePg0M/NuLazmpqTfnp1aWNdWVJMUUtEVU1HVlFKX1hTa2ZkhYCAoaCfuru609bU4OPi4uXk5uro4+Xj3+Hf3uDd3+Hf3+Hf3N/d3uDe4eLg4uPh4OHf4OLg4eLg4OHf4OHf4eLg5ufl5ufm3+De3d/c3t/e4OPg3eHg4OLi4ePjfHhzW1JLZF1WzM3N6+7uYmlnDxQQEhcTDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEBURDxQQFhwYwMXG09TUU05MUklGV09MTUQ+TERAXFZTcWxnbmhkV05LVk1IVUtJl5OR3t7d4+Xj2tnXxMPBq6mmkY6Jd3JuZFxZV05JUUlCUElDVlBLYl1YdHFrjIqHpqalxMXE09XU4uTk5uno5unn5Obl3uLg293b3uHf4OHf3uDe3+Hf4eTi4ePh3N/d3N/d3+Hf4OHf3d/d3uHf5ujm5+ro5ujn4eHfysrHzMzJ4OHf3N7c3+De4ePh4eTh3d/e5OjmsLCtW1NMW1JMrauq8fPzjJGQDxQQERYSDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEBURDxQQJCon1NfYx8jHUElGVkxJUEdDX1dWmZeWysvK3Nzc3d3dt7W0ZV5ZWlFKVk5IbmZie3dybWVhXFNOUUpDT0dBU0tIXFVSamRgf3x5mZeVtba0yczL2dvb4+Xl5ujo5ujn3d/f3d/e3d/f3+Lg4OLg3eHf3uDe3+Lg3+Hf3uDe3uHf4OLg3+De293b3+Hf5ufm5+ro5efl2tzaysrHr62pk5CLfnh1XVVRiYWB5Obk2tza3+Hg4uPh4eLg3N/d4+blubm2XFVNWVBLpKOi8vT1lpubDxQQEBURDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEBURDxQQICUiz9PTzM3MUkxJT0dDa2dkzMzM5+fo4+Pj39/f3t7e7O3tuLazWFBKXVVOVEtET0ZAVExHYFpUcm9rjImHqKakwcLA1dfW4uXl5+rp6ero4OLh3N7e3N7e3uDe4OHg3d/e3d/e3uHg3+Lg3uLf3eDe3d/d3uDe297c3N7c4uTi6evp6evp4OLh19fVxsXCqqijjouGeHNtZ2BaW1VNW1RMY1pUYllUaWJdz9DO4OLh3N7c3+De3d/d4OPh5OjmiIWBW1NMXVdQvLy68PPzhouMDxQQERYSDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQERYSDxQQP0NB6ezsqKenSEJAUEtIubi45+fn3Nzb3t7e39/f3t7e4ODf3d3ca2RhX1lVe3Zyl5OSsbCux8jH3t/d6Onn6uzq6Orn5Obk4eLg3+Hf4ODg293d3d/f3N7e3+Hg4ePi3N7f3t/g3uDf3d/e297c3uHf4eTi4+bl5ejm3+Hf1tjUwsK+paSfiISAc2xoZV5XW1NMWE9IW1NMX1xVb25odnVvZV9aXlZPXVVOfnp10dHP4uXj5unn5Ofl1tfVkI+MW1RNZFtUWlJMs7Kw8PPzk5iYDxQQEBURDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEhcTDxQQVllX8/X2kY+PRD48XldW0NDP4ODg39/e4ODf4ODg39/f4eLg4OHfxMTC0tLS5Obk6uvq6ero4+Xj4+Ti4eLg4eLg4uPh4uPh5OXj5OTi4eLi3d7e3d/f3N7e3uDg3uDe2dvb3d/g4uTj5+nn5ujm4OHfz9DOuLi1np2XgoB5bGlhYFhSWVBJVk5HWlFLYlpWcW1ohYOAoqCevsC+1djV2dvZz9DPh4V/Vk5GXVVNaWRejIiElpWQioeCa2VhWVBKXVZPY1xVWE5JnJmW7/Hxr7O1ERYSDxQQEBURDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEhcTDxQQTVJQ7/Lym5uaSEE+U0xKwL+/5ebl3d3c39/f4eHg4eLg4eHg4eLh5ufm5ufl4uPh4OHf4ODe3+De4uPh4uTi4uPh4uPh4+Ti4eLg4eLg3+Hf2t3c3N7e3uDg5Obm5+np4+Xk2tzaysvIs7CtlpKQfXVxZ2BcW1ZOU01FT0tDVVFLYlpXcm1piIaBoqKfwMG/19nX4OPi5Obl5efl4OPh3uDe4+bk3+DfkY6JXFVOVk5HU0pDU0pCU0lCU0tEZF1WdG9qYlpVWFBKoJ+c8PLyqK2tEBQRDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQERYSDxQQLzQy3eDgxMXFUElGUEdDeHJx4OHg4+Ti39/f4eLi4uPi4eLg4eLh4OHg4uPh4+Ti4uTi4OLh4eLg4uPh4uTi4eLg4eLg4eLg4eLg5Obk5+nn5ejn4uXl1tbVxcTCrKmnkIuHeHJrZV5YXlROW1NOXlVPYVlRZF1YenVzk5KPrq2twMPD0dTT297c4+bk5Obk4ePh3eDe3N7d3+Hf3+Lg3uDe3d/d4ePh5ObkvL26kpCMgHx4e3dygX14np6bv8LAfXp0XlVPXFVPv8HA7vDwkZaVDxQQEBURDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEBURERURpKio7vDxhoSCSD88UEdFeXRyzs7M5ufm4eLg4uPi4uLh4eLg4uPi4+Pi4uPi4ePh3+Df3d/d4OHf5OXj5+jm6evp6uvq5ebk1tXTu7q3oJ2XhoF9cGhjYVlSV1BIVExFV05JXVVOXVVOXVVOYVlRY1pTZF9ahIF8q6mlyMnG2NrX3+Hg3+Ph3+Hh3uHg3eDe3N/d3eDe3+Hf3+Lg3+Hf4OLg3uHf3uDe4uXj4OLh3d/e3eHf5+zr0tXTf3x4XVVOVk5HiYeE4ePk5ObmU1lYDxQQEhcTDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEhcTDxQQSk1N6Ors3d/ee3l2UUpHU0pGWVFQpKOi5+jm4eHg4uLi4eHg4+Pi4OLh3eDe4OPh5Ofl5+ro6Oro4eLgz87LtbKumZWRgHp1amRdXFRMU0tFU0lFVk9IZF1ZdnJvj4yKqKimuLi2qqmniIiDbWplX1hSWFFKVU1FVE5GXVlQb2tjhYN+oqKdv7+71tjV4+bk5efl4+bk4OPh3eDe3N7c3+Hf4OPh3eDe3uHf297c297c0tTTmpeTYltVXFNMWFBJendz1tjY7O/vpaqqExgUEBUREBURDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQERYSEBURg4eH5Ofn4+XldW9uUUdEWVJQvr685ubl4OHf4OLg4uPi4OHg4+Xj4+bl2dnYxsPAqaiijYuEdnBqYltUWE5HUUhAUUtDWVFLZF9Zd3RwlJGQr7CuzM7M3d3e5eXl6Onp5efn6evq5ujm19nXvsC+oaKghoWCbmxmYFpVV1BKVE1GVlBHYFpScmxliIV/o6Gev8C81tfU4uTj5ejn4uXj4OLg3N/d3uDe3uDe3+Phy87MXllTX1ZPXldQkpCN3d/f4uTkxcjJLTMwDxQQERYSDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEhcTDxQQQ0hG6Ovrurq5U01KTkZCnp6c6+zr39/e4eHi4ePh4ePg5uflyMnHfXt2aGNdWlJLUUhDTUQ/UEdBWVFLZ2FdfXp2mZmWtba0ys3M293d5Ofm6Orp5+fn3+Hf3N3c29zd3uDf3+Hf3d/d4OLg4uXj5Ofl4eTi19nYwMPBo6Sih4WCb2tnX1lUV1BJVEtEVk9IXVhUbWljg4F6nJqWzMvI4eTi3d/d3uHf3N/d2dza4eXjn5+bWlJMWlJLn52a5efo3uDgSlBPDxQQERYSDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEhcTDxQQgISF8/b2gXt5Rz46Z2Jf1djY4OHg4OHg4uLi4uLi3+Hf5+jnwcC/UEhCVU9HVFFKZGBdfHx5nJyZu7y60tXT4+Xk6uzr5Ofn3+Hh3N7e2tzb3uHf4eTi4OLg4ODh4OLi4eTi4+Ti4eLg3+Hf3N/d297c3ODd3+Lg4+bk5unn4OTi09bVv8HBpKWih4aDbmtnW1dUWFRNW1hPUU1Fraup5unn2dza3N/d3eDe2t3b2t7c0tXTbGdiXFNLaGNc09XV6u3taW9uEBUREhcTDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQoKOl6OvqaGNgRz47gX9+4uTk3d7f4ODg4ODf4eHh4eHg5OXky8vJW1ZPUElDmpuY297d3+Ph5unp5ejn4uXj4ePh3+Lf3N7d2tvc3d/f3uDg4OLi4+Tj4eHg4ODg4OLh4+Tj4uTi4ePh4OLg3eDe3uDe3N/d4OLg3+Hf3+De3N3c3t/f4uXk5unn4+bk1dnXwsTDfnx6WVVOYl9Yx8jG4OPh2dza2d3b297c297c2dza4eXjkI+MWlFKXFhRvb698fPzhouKDxQQEhcTDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxMQpqus5ujnZGFeRz47f3x85efm3Nzd3+Df4N/f3t7e2tra6uzrs7CtUEhDUElCmJeV3t/d5Ofl5Ofl3+Lg3eHf3+Hg4OPg3N/e293d3d/f3+Hh4ePj4+Xj3+De3+Df3+Hg4+Ti4OPh3+Hf3+Lg3+Hf3uDe3eHf4OLg4eLg4OHf3d/e3eDe3eDe293b2t3b2t3a6ezqn6GfUExFXlxUy8zJ297d0tbV2dzb2tzc2t3b2NrY4eTjoJ+cWlFKXFVPt7i28fPzh46ODxQQERYSDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEBURDxQQl5uc7/LydXFwSUE+WVRSycnJ6+zr4+Pj4+Pk5ebm6erqy8zKZGBcTUdDVExITUdEXlpXiIaCtrWz19jW5unn5enn3uHf2tzc2dvb3N7e3+Hh4OPi4uTi3+Hf3ODe3uDf4uTi4ePh3uHf3+Lg3+Hg3N/d2dza4ODg4OHf3ODe297c297c297c4ePh5efm4+bj2t3akZKPUk5IUU1JlJKP4+bl2Nva19rZ2NvZ2dza297c5ejniIaBW1JKX1pUxcbG7fDwfIGBDxQQEhcTDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQERYSDxQQa29v8vT0rq+tRkA9TURCYVtapqOiw8LCx8bGu7q5lZOQWVRRSURBTklGTEdETUhFS0ZDR0I+S0dDYFxZhoKAt7e14eTj293d2tzc3N7e3uDg4ePi4uTi3+De3eDe3N/e3uHf3+Hf3uDe3+Lg3+Hf3N/d19rY3+Df3+Hf2t3b2d3b4eXj4+Xk0tPQtLOvj4uJaWViVVBNVVBNVVBNU05Lj46LzM7L293b3eHf3ODe1NfVnZuZX1pTW1FKenVw3+Hh5OfnV15dDxQQEhcTDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEBURDxQQKi8uzdDS5+npkpGRU0tJT0ZCSkE/UUpHUUxKS0ZDRUA8S0ZDS0dESkVCSURBSkVCTEdETklGT0pHTEdESkVAT0hFgn991NbW3d/f297e3d/f4eLi3+Lg3eDe4+bk5Ofl4+bl4+bk4+bk4eXj3t/d3uDd3eDe4OLh3N/d3eHf4OHgu7y5iYaCYV1YT0tGS0ZDTklGUUxJUEtIUUxJU05LT0pGYVtYd3Rvgn98fn14ZmRfW1NOYllSXVdRvLy76erqwcXFICYiDxQQEBURDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQERYSDxQQXWJi4+Xl3uDfb2xqSURBUEpHT0dESENATUhGSURBRkI+SURASENAR0I/SENASENBSkVCSkVCTUhET0xHU05LR0I9iIiF4OPj2Nra3d/f3d/f4eLi2dvZx8jEx8bBx8fEyMfEx8bD09PR4uXi3uDe3N/d3uDe4OLhycnHfXh1VVBLTktDUk5IVE9MU05LUUxJT0tHT0tIUEpIUUxJU09MSkZCUEtHTkpFSUU/WFVNWVVOVVBLqKim4+bm4uXlZWxrDxQQERYSDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQERYSEBURPEFA5+rrqqmoSENCvL28enV0WVNTuru6UExLg4GAm5qXQTw4R0M/R0I/R0I/R0JBR0I/R0I/SURBS0ZCTkpFUExIV1RPyMrJ3ODg29zc4OPj0NLOdnBqXFVOX1dQYVdQYFhRYFdRZFtWrauo4OLg2t3b3eHf2t3bb2xpSkVBVE9MU09LUk1JUUxJUEtITklGTUlFTUpHTkpHTUhFW1ZTmpuZW1lXZGNdlZaST0tJe3l1jYyLamll09TU6uzsY2ppEBUREhcTDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQERYSDxQQOj8+4uTlvLu7S0dF0tXUxcbGrK6t6errpaam2dvboJ+bPTg0SENARUA+RUA/RUA/R0I/R0I/R0I/SURBSkZDUEtISURAo6Wj4OTk2NrZ5Ojmj4yHUUdAXVVOV05HVUxFVk1GWlJLV09IaGJd09XT297d3+Hgz9LPXlpXUU5HUE1HT0tHTklGTEdETEdES0ZDTEZESkhETElGSUVCYl1Z4uXjnqCfoKCf5OjmjY2Lzc/Nr7KwTUtEw8PC7/LyhIqLDxQQERYSDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEBURDxQQGR8cvsLD5ebmYF1bcm5v4eTk6Orr3+Li6+3txMXDUk5LQz47RkE+REA9RD8+RUA/RkE/RkE/R0I/R0I/R0I/TUdESkE9gYB93+Li2dva5ejmiYaBU0tDXVVQbmtmgH56e3h0Z2BdWlBKaGNd1dfV297c3N/dzM7MXVhUT0tFUExGTkpGTEdESUZCSERBSERBSEZCR0ZCSkdDTEpGSUdDo6Of5uro3ODe1tnX4uXk3eHfd3VyWVVQy83M6+3ueoGBDxQQERYSDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQERYSDxQQen+A8vT0wsTEaGVmcnFxnZ2cqKmojYyJT0tIQj06RkE/RD8+RD8+RD8/RD89Qz48RD89RUA9RkE+R0I/SkRBTUM/Yl5az9TT3N/d4uXjvb+7U01GaWFd19nX6evp6Orqu7u5UEhDoJ6b3+Ph2dzZ4OPiuLi3TUlET0tHTUhFTEdESURBR0I/R0I/R0I/RkNARkRAR0VBSkdDS0dET05KlZWRxcXCyszLxMfDh4aBSEM9gYB/4ePj4uXlT1dUDxQQERcTDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEBUREBURISYksLO28vT05efnwcPDrq6uVlFPODMwRT89RUA+Qz49Qz49Qj49QT08Pz48QD46Qz48RD48RD88RUA9SUI/T0ZDS0ZCtLe14eXk2t3b3ODetbSya2dkbGdifXdyfHdzdG9tn5+c3uHg297c2dza4uTkjo2KSEE9TUlESUVAR0I/R0I/RUI/RkI+RkE+RkE+RkI+RkM/R0RAS0dDTEhFR0RAVVFNW1hSTktDS0hBe3p1ztDQ6Orqtbq7GiAdDxQQEBURDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEBURDxQQICUje3+Azc/Q5Obm4+XlvL29SkZFRD8+RD89QDw7QDw7QTs6Pzs7Pzw7QD06Qj06Qz47Qz47RD88RkE+TEVBRz45hIGA4+bl2Nva1tnY4eXj1tvYt7i2paWira+szM7N4eTj297c2t3b3N/dz9HQXlhVTUVBSkZCSEQ/R0I/RkI/REE+RUA9RD88REE9REE9Q0I+REM/R0VBSUdDT0tISURAW1dUh4aDu7y74OLi6uzr1dnaRUxKDxQQERYSDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEBURDxQQDxQQeXx88PLzqampV1NSTUhHQj08Qj08Pjo5QDs6Pzo4PTk4Pzo5QTs7Qj08Qj07RD89RUA9RD88RT88TEM/U01MxsjH3eDg19nZ2tzb297c5ejm5ejm4+bk3N/d2NvZ293c19rY4uXjkpKQSUM9TklFSkZASkVARkI9RUA9REA8RD88Qz88Qj88QkA8REE9RUI+RURASUhESEM/kI6O1NbW5efn4+Xl4OLjsrS1QUdFDxQQEBUSDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQExgUERYSXGBg5unp5+npbmpqOzU0RUA+QDs6Pjk4Pzk4Pjk5PTk4Pjk4Pzo5QDs6RT8/PDc0ODQxR0NATktISUI+PzUyend14OPi2Nva2dva297c297c2t3b2NrZ2dva297c2NnZ4uTjury5SEI+RD86RUE+QDw4PDczRUA9RUA9RD88RD89RD8+Qj48QT87QkA8QkE9RUM/SEVCTElFXFlVkpOR4OLi3uHham9vFBkWDxQQEBYSDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEBURDxQQmJ6e6+7thIOCV1NSQj08Qz48Pzo5Pjk4Pjk4PTg3PTg3PTg3Pjk4QDs5OTQxY2JhpaqouLy7wcTEur28fHp4QTo3j42K4ePk2dva2dza3N/e297c2t3b2dzb2NvZ5OflyMfFW1dTgX57r7Gvt7m5tLa1iYiIRD8+Qjw5RUA9Qz88Qz48QDw5Qj87Qj87QUA9REI+SEVBR0RAXltYztHQ4+TkxsvLHyYiDxQQExgUDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEBURDxQQnqKk7/Lyi4mJNzEwRkFAQDs6Pjk4PTg3PTg3PTg3PDc2PTg3Pzo5ODMwhYeF0NLTg4F/X1tZXlpYfHp50NPTmpiWQTk1hIN/1trY2t3c2t3b2tzb2t3b293b4ePiurq3Y15bsbCvzc3OkY+OfXl3iYWDwcG/srWzRUNAQDw5QT46QDw5Pj05QD46Qj87REA8RUA9SENASUNAYFxZpKWk6uzsvMDBGR8bEBUREBURDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQERYTDxQQUFVW4uXn5+npe3p5NzIxQj08PTg3PTg3PDc2PDc2PDc2Pjk4NjEwZ2ho2NzbZF9dS0VDRD47Qzs3PDMwX1xa2NrZdW9qPDYuenZz2Nva2t3b2dvb297c0NLQf3x5R0A8pKSivL27T0pHSEA+RTo4QTg0QTs3srKwo6alOTUyQTw5Pzo3Pjs4Pz05QD46Qz47RD88RkI/TEdEQTw5rays6+3ttLm6FRoXDxQQEBURDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQERYSDxQQfYKD7fDw297dXlxbOTQzPzo5PDc2OzY1OzY1PDc2Pjk3Mi8tqq2um5qYYV5e2dzcW1ZURDs4TkVCOzMwnJycqqqnRTw3RTw3o6Oh4eXj1djW4eTinZ2aPTQtZWBaz9HQW1dUqqqonJ2bRDw4T0dEQDo3WFNR0dPTXl1bOTQxPzo3Pjk2Pzw4Pj05Qj47RD88SENAPjs3l5eV4+Xl6OvrcHZ1DxQQEBURDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEBURExgUEBURDhMQmp+g6+3txsfHQz8+OzY1PTg3OzY1OzY1OzY1PDc1ODMzu76/cW1sjIuN6ezsfHd0OzIuTENAPzYzgH9/uru6Rj06RDs3gX584eTk1NfV3uHhgoF9PTQtgHx5uLq5XFhU19nZvL6+SENARz47R0E+QTw5vL28fX18NC4sQDs4Pjk2Pjs4Pz05Qj06RkI+PTg1kI+M4+bl6OrqnqOjGB4aEBUREBURDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEBUREhcTDxQQDxQQDxQQKi4sgoeG4OLi5+nppqamNjIwPTg3OzY1OzY1OzY1PDc2NDAvtbi5fnp6hIOD6+3tyMjIWFNQRz88ODAumJiYq6qoPzY0Qjk2enh23+Hi09bV3N7dc3BrPDIsdnJvwcPCWldUzM/P3d/flZWUPzg2SEI/Pzo3vLy8b29uNC8sPzo3Pjk2PTo2Pzo3RD88OzYzhIOA5Obm5+npqq6wHSIfDxQQEBYSDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEBURERYSDxQQDxQQGyAeXGJipKiq3d7f8vT04+Xl3uHhvb29Pjk3OjU0OjU0OjU0OjU0PTg3MCsqfn5/xcXFVVJQsrGy3eHggX58LiUiWVVU0dPUaGRiQTg0PjYzeXh23uHh1NbW1tjYZF9cQTkyT0hGzc/PdHJxfnx72Nra2draXFhWLykma2dmxMbGRkNAOzYzPTg1PTg1PTk2QDs4OzYzZGBd3uDg5ujou8DAHyYjDxQQDxQQDxQQERYSDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEhcTDxQQDxQQIiclcHR2w8jK8vX18PLyyMrKlZWVbWtqU1BPQj08OjU0OzY1OTQzOTQzODMyOTQzOTQzOzY1tbe4vsC/Z2JiXFhXTklIcm9u0dPTkI+MOTIvSD87PDMveXZ13eDg1NbWzc7PVVBNRDs4PjUxd3Vy0NPSb2xrWlZVYl9eR0JBbWpp0NHRdnd2NC8sPjk2OzYzPDc0Pjk2Pzo3PDcztrW15+nqztDRLTMwExgUMzk2KS8tDxQQDxQQEBURDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQERYSDxQQDxQQGR4cbXJ1yszQ9ff44+TkpqioaWZmPzw8Mi8uNTAvNzExOTQzOjU0ODMyOzc2NC8uNC8uODMyOTQzODQyQT08oqOj1NXWvr+/xcfI0tTUhIGBNzIuQjk2RTw4OzEudnJx3N7e19jZxMXFSUVBQjk2RDw4NzIseXh2ztDQu7y8rK2swcPC0NLSfHx8NTAtPTc0OzYzOjQyOzYzPTg1OTQxVVJO2Nra5ujplZmZe39+w8bF19ra1NfYoqioMTg1DxQQEBURDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEBURERYSDxQQDxMRWV9gu77C8/b23+Lhm5ubWFVUNDIxNDAwPDc3Pjk4Ozg3OjY1OTQzODMyOTY1OTc2Uk9PQDs7LScnNjEwPTk4OTQxMy0sT05MaGhmZmRjSENBMiwqPTc0PTc0Qjk2ODAtb21s29zc2Nvbt7i3QTo3QTg1Pjk0Pjk0Ni8sSkdEd3Z1h4eGeXh3S0hGMi0pOjUyNzIvNzIwODQwOTUyPDc0NjEuX1xZ4OLi293d19ra5+np6ezs3uDg2Nra8PLyvcHCHyUhDxQQEBURDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQERYSDxQQDxQQNzs7oKWn7/Ly6Orqn6CgVFFSNS8vOTUzPjo4Pjk4PDc1OTU1NjQzNjIxNjEwMy4tR0VERkNEODU1bWxsaGVlPTg4LSgnNjEwPDc2NC8tMCspMConNjEuPDc0OzYzOjUyQTg1OS8samVk2Nra2dzcqamoPDMwQDg1OzUzOzUzOzYzNjEuLykmLiklLyomNC8rOjUyNzIvNTAtNTAtNjEuNzQwOjYyOTQxQz48z9DQ5efn293c4+blx8jIY2NfbWpl2Nra6+3tYWVkDxQQEhcTDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQERYSDxQQFRkXen+A2t7f8vX0tri3YF5dMzAwNzMzPzo5PDg3OjU1ODQzNzQyNzIyNzExNTEvNTAvNTAvLisqcHBwR0RDKSQkX15dh4eIc3FxREA/LScmMCspODMwOjUzOjUyNzIwNzIwOTIvQDc0OC8sX1xa09XW3N7emZmXNS0qPTc0ODMwNzIvNjEuNzIvODMwODMwODMwNjEuNTAtNDAtNDAtNTAuNjAuNjIuNzIvOzYzNC8sbGln1tjY5ejnvr/AUk5MPzozTEU9xcXE7vDxhomJDxQQERYSDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQERYSDxQQLDEvpquu8/b219nYe3p6NzU1NDExPTg5Ojg3OTU0NzU0ODQ0NTIyMzEwNTExNDAwMy8uMy8uMzAwLSsrOzs7m52dR0JBJB4dOzc2aGhok5OSh4WFWlhXNjEuKyUjLikmNTAtOTQyOTUxPjYzNjAtU1FPzM7O293diIiGMSsoOTUyNzIvNTAtNTAtNTAtNTAtNC8sNC8sNC8sNTAtNC8sMy8sNC8tNTAuNTAtNTAtNjEuOjUyNS8sS0hFZWNhREA9Pzo4SEQ9SEE5vL278PLykpWVDxQQEBURDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEBURDxQQMTY2w8jJ8/X1srKyTUtLMC4tPDg4Ozc4NzY2ODY2ODU0NDIyNDIyNDIyMjAxMS8vMC4uMC4tMC4tMC8tMjAvKiUkVldXuLu7UU1MKiMjLikoNjEwXlxbiImKlpWVf3x8WVRSOzY0LCckKyYjMiwpNC8rSUZEztLR6e3se3t5MCsoOjUyNTAtNTAtNTAtNTAtNC8sMy4rNC8sNC8sNC8sMy4sMy4tMy4tNC8tNC8sNC8sNTAtNjEuOjYzNzIvNTAsPTg1QTw4QT44SUM8xcXE7/Hyio+ODxQQERYSDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEBUREBURHSIgtbm88vTznJ2dNjQ0NTMzOzo6OzY3ODU1NjQ0NzU1NTIyMzExMjAwMjAwMTAwMC0uLy0tLy0sMC4tMC4tMC4sNDExKCIiaWprztHRbWtpLSgoMy4sMSspLSgnQT4+aWdni4uLl5eWiYeHcGtrU09MPjk1NC8sXFlYi4uKU09NKyUiMy4rMSwqMy4rMy4rMy4qMy4rMSwpMSwpLyonLikmLiomMC0rMi4tMy4tMy4tNC8tNC8tNTAtNTAtODMwPDc0PDc1QDo2PTkyWFVQ2NnZ6ezsc3d2DxQQEhcTDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQERYSDxQQe3+C9Pf3qaurMzExODc3Ojg4ODY2NzU1NTMzNDIyNTMzMjAwMjAwMS8vMS8vMC4uLy0tLy0tLy0tMC0tMC0sMS4sMC0tMzAvJiIiZ2pr2t3dnZybQT08LCclNTEvNTAvLCcmLCcmPTk4WldXeHd2jY2MlZaVkZCPfHp3a2hkYV9cVlNPSkZDQz47PTo2OTQyOTMxODMwOjUyPTg2QDw5RUI+QUA8MzAvLy0sMi0rMi0sMi4tMy8rNC8sNTAtNjEuOTQxOzYzPzs4NC8piomG5ujp3+LiSE1LDxQQEhcTDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEBURDxQQIygnzNDT29zcTEtLNDIyOjg4NzU1NzU1NDIyMzExMzExMzExMjAwMS8vMC4uLy0tLy0tLy0tLy0tLy0tLywtLywsLywsLy0sLiwsMTAvJiMjVldWyM3M0dTTfnt6OzY0KiUkMS0rNzIxNjEuLiknLCQkLygoOjU1TElHYWBec3NxfX58hYaFjI2LjY2LjI2MjIuLiYaFhIOBfn19d3Z1Z2dmUE1MPjw7RkNDNDIxMSwrMi0sMi0sLy4rMi4sNTAtNTAuNjEuOjUyNzIuSUVBz9DQ6OrqvcDAGB4aDxQQEBURDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQERcTDxQQUFVY7vHyqaqqMS8vOzk5NzU1NjQ0NTMzMzExMzExMjAwMjAwMC4uMC4uMC4uLy0tLy0tLy0tLy0tLy0tLiwsLy0tLiwsLSsrLSorLiwsNC8vKyYlOjg4l5ma3+PjycvKhIOBSkdFLyknKiUiMiopOjAwOTMyODAwMi0rLikmLSckLCYkLSgmMCsoMy8tNTIwOTYzOTUxNTEuLCgnIh4cJyEeTkpKamppRkNCLSopMS0rMSwrMS0rMC0rMC0qMy4rNS8sNjEuNzIvPDg0tbW14uXk4ePkXmNiDxQQERYSDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEhcTDxQQaW1w8/b2k5OTLy0sPDg5ODQ1NTMzNDIyMjEwMjAwMjAxMjAwMC4uLy0tLy0tLy0tLiwsLy0tLiwsLiwsLiwsLiwsLiwsLysrLSkoLyopMSwrNC8uMCopKSQkVFNUpamq2+Dg2drar62tenZ0UUtKOjIyLignKiQjKiUkLSgmLysoMSsoMCsoLikmLCYjKSMhKCIfJyIeLyonSURBd3RympqZf39/Pjs7LCYkMS0rLywqMCwqMCwqLywpMSwqMi0rMi8sNTAuNjEtOzY0wMHA4+bm297eSExLDxQQFBkVDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEhcTDxQQZmps8/X2nZ2dMC4tOzg5ODU1NTMzMzExMzExMjAwMjAwMS8vMC4uLy0tMC4uLy0tLiwsLiwsLiwsLiwsLSsrKykpLSsrLCoqLCopLSopLywrMSwrMy4tNC8uLCYlLCgnUk9QkZGSx8vN3uPj2NvbxMTEpqSkioiHcW5tX1xaVlFPUEtITklGUk1LWVZTZ2Rjf3x7nZyauLe1uby6kZGSTUtLKCMiLignMSwpMCooLiknMCsqMCwqLSwpMC0qMSwqMS4rNC8tNjEwMCsoUE1K09XV5ujoys7ONTs5DxQQEhcTEhcTEBURDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQERYTDxQQSk9R6ezturu6NjQ0OTc3NjQ0NDIyMzExMjAwMjAwMS8vMC4uMC4uLy0tLy0tLy0tLy0tLiwsLCoqLCoqLCoqKykpKykpKykqLSkpLSkoLCkpLCopMCsqMSsqMy4tMy4tLCYlKSQjOjY1W1pahoeHrLCwyczM2N3d3OHg3OHg297e2dvb2d3b2dzb1trZz9LSvcDAm52ea2trOzk4JSAfKyYkMi0sMCsqLionLyonLyonMS0rMS0sLysqLisqMCwqMS0rMi0sNC8tNzIvLyomWlhW1dfX6u3sy83NTFFPDxQQDxQQDxQQERYSEBURDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEBUSDxQQKzEx09bY3d7eUE9PNDIyODY2NTMzNDIyMjAwMjAwMC4uMC4uLy0tLy0tLy0tLiwsLiwsLiwsLCoqKykpLSsrLCoqKigoKigoKykpKigoKigoKykoLSkoLysqLyopMCsqMi0sNC8uMCsqKiQjJyIhLCgoOTY1SUdGWFhXZmZlb3FwdHN1bm1uY2RjVFRTQj8/MSwrJyEfJSAeLSclMSwpMCspLiknLyonLiknKiUiKyYjIhwaIx4dLiknLiooLyopMCwqLi0qMC4qMy0qNzIvLiklV1NRysvL7vDw4uPjkJKSTVBOISUiDxQQDxQQEBURDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEBURDxQQExgVrK+y8PLyhYWFLSsrOzk5NzU1NDIyMjAwMjAwMS8vMC4uLy0tLy0tLiwsLiwsLy0tLiwsLSsrLSsrLCoqLSsrKykpKigoKigoKigoKigoKygoKyknLSopLSknLSgnLikoLyopMCsqMSwrMi0sMSwrLignKyUkKCMiJyEgJiEgJiEeJyEfJiEgKCMiKyYlLyooMSwrMCspLCgkLCckLSgmLSgnLCckMCwrQz8+ODQzfnx8cm9vLCgmLSgnLiknLikmLiooLywqMSwqMi0qNzIvLyonQz89paSk4uXl9Pb26+7uyMvLh4uKHSIeDxQQEBURDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQERYSDxQQaW1w7vDwxcfHPDs7ODY2ODY2NDIyMzExMjAwMS4wLy4uLy0tLy0tLy0tLy0tLiwsLiwsLCoqLSsrLCkqKykpKikpKigoKScnKignKigoKignKignLCgnLSgnLCkoLCcoLScnLScoLSgnLSgnLigoLikoLikoLyopLyopMCsqMCsqMCsqLyopLikoLSgoLSgoLCcmLCcmLCclLCckLCgkLScmMS0snJubvr6+qamplpOUtLOzg4B/Ix4cLyonLSgmLSglLykoMCsqMSwpMi0qNjEuMy4rLyonZWFfo6KixMbF4+Xl8fTzpqqpGh4bEBUREBURDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEBURDxQQICUkwcXH7O7ugICALSsrOzk6NjQ0NDIyMzAxMi8xMS8vMC4uLy0tLywtLy0tLiwsLiwsLCoqLCoqLCoqKykpKykpKigoKigoKigoKigoKignKykoKykpKygnLSgnLSgnLScnKygnLCgnLCgnKycmLSgnLSgnLCcmLCcmLCclLCcmLCcmLCcmLCcmLCclLSgmLSgnKyYlKyYlLCcmLiknIh4cc3JxqqqqTUpJvLy8LiwrXFpara2sIx4cLiknLSgnLCglLSgmLikoMCsqMSwpMi0qNC8sNjIvMikmMywoOTMwfHp44OHh5efoTlJQDxQQERYSDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQERYSDxQQbXJ06u3u09XUTUxMMzExOjg4NDIzMzAyMjAwMS8vMC4uLy0tLy0tLy0tLiwsLSsrLCoqKykpLCoqKykpKigoKScnKigoKScnKigoKicnKicoKigoKigoLCcoKignKicmKScmKCcmKycmKycmKyYlKyYlKiYlLCcmLCcmKyYlKyYlKyYlKyYlKyYlKyYlLCcmKyYlKyYlKyYlLSgnIRwbdXNzmpqbmJaWw8TErq6uubi4aWZlJR8eLikoLSgnLCcmLCclLSglLikmLikmLyonMi0qNS4rOjEuPjUyOC4qTUlF2dvc5OfnZWppDxQQERYSDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEBUREBURHiMitrq97O/tt7m4OTc3NjQ0OTc3NDIyMjEwMTAwMzExMC4uLy0tLy0tLy0tLiwsLSsrKykpKigoKigoKigoKigoKScnKScnKScnKScnKScnKigoKicnKyYnKyYnKiYmKSYlKCYmKSYlKyYlKyYlKSUkKSUkKiUkKSYlKyUkKiUkKiUkKiUkKiYlKiUkKyYlKiYlKiUkKiUkKiUkLCcmIx8eiIiHlpSULisrxcbGdHJxFQ4NKyYlLikoLCcmLCclLCckLCcmLCclLCckLikmMCwpNCwpNy4rOjEvMiklY2Bc4eTj4+XlXGBhDxQQERYSDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQERYSDxQQREhL1dna6uvqrq+vOjk5MzExOjg4NTIyMzExMjAwMS8vMC4uLy0tLy0tLiwsLCoqKykpKykpKykpKigoKScnKScnKScnKigoKiYnKScnKScnKicmKyUmKiUmKCYmKSYlKiUmKCYmKiYlKiUkKCUkKiUkKCQjKCQjKSQjKCMiKSQjKiQjKiQjKiUkKiUkKSQjKiUkKSQjKSQiLCcmIRwbWFVVtrW1jIuKq6yskpGRf359U1FQJSAfLSgnLCclLCcmLCcmLCcmLSgkLSglMSsoMywpNi0qOzIvLyQijImI6ezs1tjZODw7DxQQERYSDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQERYSDxQQZWlt4OPk6erqury8TUxMLiwsOzc4NzIzMzAwMS8vMC4uLy0tMC0tLy0tLiwsLSsrKykpKykpKigoKigoKScnKigoKigoLCYnKicnKiYnKSYmKyYnKCYmKSYmKCYlKCUlKSUlKiUkKSUkJyUkKiUkKSQjKSQjKSQjKCQjKSQjKSQjKSQjKSUkKSQjKSQjKSQjKSQjKSQjKiUiKyYlJiEfWldWmJWVrq2tzc3Oq6urREFBKCMiLSgnLCcmLCcmKyYlLCcmLSglLCglMSonNiwpNi0rOC8rNi8qvb287O/vs7W1EhYTDxQQEBURDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEBURERYSDxQQZmxv2dzd6uvq0tPTcXBwLywtNTMzNzQ0Mi8vMS8vMS4uMC4uLy0tLy0tLSsrLSsrLCoqKigoKykpKicoKigoKigoKigoKicnKyYnKScnKSYmKScmKCYmKSYlKiUmKSUlKSQkJyQkKCUkKSQjKiQjKiQjKCQjJyQjJyQjKCQjKSQjKCQjJyUkKCQjKSQjJyQjKCQjKSQjKSUjLSgnGhQTWldXlZSURkVEJCAfJyIhLSgnKyYlKyYlKyYlKyYkLCcmLSgnLSgmLikmMywpOC8sLyYiY19b4ePj6evrd3p4DxQQEhcTDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEBURDxQQUFZYxsnM6evr4+bln5+gPTw8LywtNzU1MjAwMi8vMS4uLy0tLy0tMCwsLiwsLCoqKykpLCgpKykpKigoKigoKikpKycoKycnKicnKyYnLCYnKiYmKSUlKiUlKiQlKiUlKiQkKSUkKiUkKSQjKCQjKCQjJiQjJiMiKSQjKCQjKSQjKSQjKCQjKCQjKSQjKCMiKCQjKSQjKSQjLCgnKSUkIBwbJSAeLScmLCcmLCcmKyYlKyYlKyYlLCclLCclLSgmLikmMSonNCwpOTAtLyYksbGw5ujo19naOTw6DxQQERYSDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQERYSDxQQLTMzo6es5ujo6uzrxcfHWFZWLykqOTU1NS8wMi8vMC4uLy0tLywsLiwtLSsrLCoqLCgoLCkpKigoKykpKykpKigoLSgoLykqLCgpLCcoLigpLCcpKSUmKSQlKSUlKSUkKCUlKSQkKSQjKSQjJyQjKCQjKSQjKSQjJyMiKSQjKSQjKSQjJyMiKCQjKSMiKSQjKSQjKSQjKSQjKiUkLCcmLCcmKiYlKyYlKyYlKyYlLCcmKyYlLCclLCckLSgmMCkmNSwpOTAtKyIfbWln4+Xl5efnmJucEBUREBURDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEhcTDxQQFx0bfoGG2Nvc6Orq2tzcaWhoLyoqOjQ1NS8wMy4vMC0tLy0tMCssLissLSsrKykpLSkqLCgpLSgpLigoLyorJiIiHhsbJiEiKiUmJB8gIBwdKyYnLCYmKyUlKiUlKiUkKCUkKSUkKSQjKCMiKSQjKSQjKCMiKSQjKSQjKSQjKCMiKCQjKSQjKSQjKSQjKSQjKSQiKSQjKSQjKSQjKiUkKSQjKiUkKiUkKyYlKyYlLCclLCcmLSclLCclLykmNy4rMCckRT060dHR4eTk2drcPkFBDxQQERYSDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQERYSDxQQDxQQTFFSv8PF5+np3uDgY2JiMCwtODQ0Mi8vMi4vMS0uMSssLywtLiwsLisrLyorLigqLyorLCgoIh0eSUdHe3t7h4aHgoKDfXt9YV5eKCMjJyIiLigoKyUlKyYlKyUkKSUkKSQjKSQjKSQjKCQjJyMiKCQjKSQjKSQjKSQjKSQjKSQjKSQjKCMiKCQjKCQjKSQjKSQjKSQjKiUkKiUkKyYlKyYlKyYlLCcmLCclLCckLSglMConNS4rMiglODAtvLy74eXk5ujog4WFDxMQEBURDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEBURERYSDxQQLTIytrq86Orp0dPTSUZGMzAwNTEyNC8wMy4uMSwtMCwtLissMCssMSorMy0uKiQmLy4uiIiJlpaXXl1ePjs7NjMzPjs9bGxukpOUNzIyJyEhLikoKyYlKiUkKiUkKiUkKiUkKCQjKCQjKCQjKSQjKSQjKSQjKSQjKSQjKSQjKCQjJiMiKCQjKSQjKSQjKSQjKiUkKiUkKyYlKyYlKyYlLCclLCclLCclLSckMSonOS8sMCYjPDQxuLi34uXl5efmrbCyHyIgDxQQEBURDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEhcTDxQQMDY2xsjL7O7tpqWlMissOTM0NTAxMi8vMi0uMiwtMSssMSssMy4uKyYmPjs7m5ycZ2ZmJCEhJB4fLCUmLScoKiMkHBcXUE9Po6OjMi0sKyYlLSgnKyYlKiUkKiUkKSQjKSUkKSUkKSQjKSQjKSQjKSQjKSQjKSQjKSQjKCQjJyQjKCQjKSQjKSQjKiUkKiUkKiUkKiUkKyYlKyclLCckLSglLiglMionOC8sKiIfSURBxcXE4uXl5efnur2+MDQzDxQQEBURDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEhcTDxQQVllc4ePk4+XkZWBhMSssODM0My8wMy4vMi0uMi0tMy4uLigpPTg4lJSURUNEIxwdMy0uMi0sLyopLigpLigpMiwtHhcYX15eoqKiJB8eLSgnLCcmKyYlKyYlKiUkKiUkKCUkKiUkKSQjKiUkKiUkKiUkKSQjKSQjKSQjKSQjKCQjKiUkKiUkKSQjKiUkKyYlKyYlKycmLSclLCckLiglMSsoNy8sKSAdYFtZ1NbV4uTk5ujos7S2JyspDxQQERYSDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEBURERYSEhcUoaSn7/HxsLGxMy8wOjQ1NzAxNS8vNC8vNC4vMy4uMy4uiIaHR0JDKCIjNS8wMCosMCsrMCsqLyopLikoLSgnMi0tHhkZgICAjIqLHRcWMCsqLCcmKyYlKyYlKyYlKyYlKiUkKiUkKiUkKSQjKSQjKSQjKSQjKSQjKiUkKiUkKiUkKiUkKiUkKyYlKyYlLCcmLigmMSgmLykmMiwpMSwpKSEed3Ry4OLh4ePj5Obmm52fICQiDxQQERYSDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQERYSDxQQSEtN3uDi4ePiXVtcMywuOjQ0NzExNS8wNzIyLScoWldXV1VVKyUmNjExMiwsMSwsMSwsMSwrMSwrLykqLSgoLikoMCsqIh4dl5iYdHFwHRgXMSwrLCcmLCcmLCcmKyYlKyYlKyYlKyYlKiUkKiUkKiUkKiUkKiUkKSQjKiUkKiUkKiUkKyYlKyYlKyclLigmMSgmMiklNi0qMyonLykmk5KR4+bm4ePi3N7fen1/FRkXDxQQERYSDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQREBUREhcVpaeq8fTzn5ydMisrOzY2ODMyNzExNC4vQz4+goCAKyUlODMyNjEwMy4uMi4sMy4tMi0sMi0sMSwrMCsrLyopLyoqMCopKiYlnp+ga2lpHhkYMCsqLCcmLSgnLCcmKyYlLCcmLCcmKyYlKyYlKyYlKyYlKyYlKiUkKiUkKyYlKyYlLCcmLCYmLicmMSgmMikmNy4rMCckPTYzsrKx5unp4uTkztDSVlhaDxMQDxQQEBURDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEhcTDxQQWF1d6ezsz9DQR0JBODMyOjU0OzU2LykpbWpr7O7uj46NMSwrMy4tOjMyNS8uMy4tMi0sMi0sMi0sMi0sMSwrMSwsMi0sMCsqLCkonZ2ddnNyIBsaLyopMCsqLSgnLSgnLSgnLCcmLCcmLCcmLCcmLCcmKyYlKyYlLCcmLCcmLCcmLSgnLCgnLygmNCsnNy4rMSclQTs4wcLB5efo4+Xlu72+Oz8+DxQQDxQQEBURDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEBURDxQQISYjxMfJ6+3tcW5tMy0sPTc3PTc3Mi0trKys5ujo5unorq2tSkNCMicnOTExNzMyNTAvNC4tMy4tMi0sMy4tMi0sMS0sMy4tMSsqKyUlj4+Oi4mILCcmKSQjMi0sLyopLiknLSgnLSgnLSgnLSgnLCcmLCYmLScnLSgnLCgnLSgnLignLikmLyonOC8sMSglQDo3xcbG4+bm4+XkpqmrKS0tDxQQERYSDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEBURDxQQjJCS9Pf3oJ6eNC4uPzo5OjIxT0hK2NnZ3uDg19nZ5ujo0NLRfXl5OjQzLykoNjAvOTIyNjEwNy8vNC8uMy4tNC0sMi0sMy8uMi4tJyAgdHBwnZ2dTUlIKCIhMi0sMy4sLiooLyoqLykoLikoLSgnLygoMCcnLSgnLikoMCkoMysoNCsoNy8sMikmPTYzwMDA4+bl5ObmoKKlHSEfDxQQERYSDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEhcTDxQQUFVT6eztycnJRj8/RTw8Niwsh4aF6Ovr2Nra5ujp297e6evr6Orqu7y7c25vQzw7LSgnLSkoNS0sOTEwOjIxOzExODIwODExOTExPTQzLSMjTUlIlZSTcW5tLikoKyQiNS0tNS4uMSwrMCsqMCsqLyooMCsqLyopMCsqMywpNCsoOC8tMiglOzQyu7u64+bm5OblpKanHSEgDxQQERYSDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEBURDxQQGyAcwcXG5ujoX1hZMicnQzs6yMrJ4OLi5efniY6NQUVDm5+g4OLk5+no5OfmysvLl5WVZ2NiSD9AOi8vMigoMCYkLyYlLyQlLyUlLiQkMigoMCYkNzEul5eWvb6+YlxbMicnLSQkNC4uNTAvMy4tMi0qNSwqMywrMi0sMi4rOTIvMCckQz06wMHA4+Xl5Oblra+xJCgnDxQQERYSDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEBURDxQQnaGg7e/vtbW1b2prqKam3+Hh5+npfYKBDxQQDxQQDhMQUlVXp6mr3d/h7O/u7e/v4+bm0NHRuLe3npycjYqJgn5+fnp4gHx7ioiHm5mZtLSzzc7O19nZ5ejn4+blr6+vZ2FhNi0tLSMiMyomNy4rOTAtOTAuOS8tNC0qKiIfU0xKysvL4uXl5Ofms7W4Ki0tDxQQERYSDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQERYSDxQQYmZl6uzt5Ofm5ujo4+bl7O7ut7q6FBoWEBUREhcTDxQQDxQQFBkWT1NVl5qcxsfJ4eLj6+3t7vHx7/Ly7O/v6+3t6u3s6uzs6+7u7O/u7O/v6+3t6evr1dfY3d7f8fTz5efnu7u7gn17UktJOzMxNSsoNSsoNy8sRT47gX1619nY4ePj5ebmqayvKC0sDxQQERYSDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEBUREBQRdXd50dLU3N7e2drcrK6wLzMyDxQQERYSDxQQDxQQERYSDxQQDxQQDxQQJywqVVhaenx/nqCis7W4xMXHy8zOztDRzs/Ry8zOxcbIs7W3m5ydcnR3PUBBS05On6Gk2dvd7/Hx6+7u2tzcwsPDs7Kxrq2suLi4z9LQ5Ofm4eTk5efnmpydICQiDxQQERYSDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQKy8tREdHOz8+ExgUDxQQEBURDxQQDxQQDxQQDxQQEBURERYSDxQQDxQQDxQQDxQQDhMQFxwaKCsrLTAwMDU0Mjc2LzQzKCsqGR0bDhMPDxQQDxQQDxQQEBQSRklJj5CSycvM5Obn7vDw8PLy7/Ly7vHx6uzs5Obm0NLTd3p7GBwaDxQQERYSDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEBURDxQQDxQQDxQQDxQQEBUSDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEBUSERYSERYSDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQERYSERYSERYSDxQQDxQQDxQQKi4sWl1dhoiKmp2foqOmm5+fioyMaGprODs6DxQQDxQQEBURDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEBUSERYSERYSEBURDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEBUREBUREBUSERYSERYSERYSEBUREBURDxQQDxQQDxQQDxQQDxQRERYSDxQQDxQQDxQQDxQQDhMPERYSDhMPDxQQDxQQDxQQDxQQEBURDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEBURERYSEBURDxQQDxQQDxQQDxQQERYSERYSDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQEBURDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQDxQQ`

var botoloBMP = func() []byte {
	b, err := base64.StdEncoding.DecodeString(botoloBMPBase64)
	if err != nil {
		return nil
	}
	return b
}()

var (
	clsidFileOpenDialog = GUID{0xDC1C5A9C, 0xE88A, 0x4DDE, [8]byte{0xA5, 0xA1, 0x60, 0xF8, 0x2A, 0x20, 0xAE, 0xF7}}
	iidIFileOpenDialog  = GUID{0xD57C7288, 0xD4AD, 0x4768, [8]byte{0xBE, 0x02, 0x9D, 0x96, 0x95, 0x32, 0xD9, 0x60}}
)

func u16(s string) *uint16 { p, _ := syscall.UTF16PtrFromString(s); return p }
func textOf(h uintptr) string {
	n, _, _ := procGetWindowTextLengthW.Call(h)
	if n == 0 {
		return ""
	}
	buf := make([]uint16, int(n)+1)
	procGetWindowTextW.Call(h, uintptr(unsafe.Pointer(&buf[0])), n+1)
	return syscall.UTF16ToString(buf)
}
func windowsText(s string) string {
	s = strings.ReplaceAll(s, "\r\n", "\n")
	s = strings.ReplaceAll(s, "\r", "\n")
	return strings.ReplaceAll(s, "\n", "\r\n")
}
func setText(h uintptr, s string) {
	procSetWindowTextW.Call(h, uintptr(unsafe.Pointer(u16(windowsText(s)))))
}
func replaceOutput(s string) {
	if hOutput == 0 {
		return
	}
	procSendMessageW.Call(hOutput, WM_SETREDRAW, 0, 0)
	procSetWindowTextW.Call(hOutput, uintptr(unsafe.Pointer(u16(""))))
	if s != "" {
		procSetWindowTextW.Call(hOutput, uintptr(unsafe.Pointer(u16(windowsText(s)))))
	}
	procSendMessageW.Call(hOutput, EM_SETSEL, 0, 0)
	procSendMessageW.Call(hOutput, WM_SETREDRAW, 1, 0)
	procRedrawWindow.Call(hOutput, 0, 0, RDW_INVALIDATE|RDW_ERASE|RDW_FRAME|RDW_UPDATENOW)
}
func move(h uintptr, x, y, w, hh int) {
	if h != 0 && w > 0 && hh > 0 {
		procMoveWindow.Call(h, uintptr(x), uintptr(y), uintptr(w), uintptr(hh), 1)
	}
}
func message(s string) {
	procMessageBoxW.Call(hwndMain, uintptr(unsafe.Pointer(u16(s))), uintptr(unsafe.Pointer(u16("Kunta"))), 0x40)
}
func scale(v int) int { return v * currentDPI / 96 }
func setDarkTheme(h uintptr) {
	if h == 0 {
		return
	}
	procSetWindowTheme.Call(h, uintptr(unsafe.Pointer(u16("DarkMode_Explorer"))), 0)
}
func setImmersiveDarkTitlebar(hwnd uintptr) {
	on := int32(1)
	// 20 is DWMWA_USE_IMMERSIVE_DARK_MODE on current Windows 10/11; 19 on older builds.
	if r, _, _ := procDwmSetWindowAttribute.Call(hwnd, 20, uintptr(unsafe.Pointer(&on)), unsafe.Sizeof(on)); r != 0 {
		procDwmSetWindowAttribute.Call(hwnd, 19, uintptr(unsafe.Pointer(&on)), unsafe.Sizeof(on))
	}
}
func fontForID(id int) uintptr {
	switch id {
	case ID_TITLE:
		return fontTitle
	case ID_TAGLINE, ID_HINT, ID_STATUS, ID_LABEL_OPERATION, ID_LABEL_PARAM, ID_FOOTER:
		return fontSmall
	case ID_EDIT_INPUT, ID_OUTPUT:
		return fontMono
	case ID_RUN:
		return fontBold
	default:
		return fontUI
	}
}
func create(class, text string, style, ex uint32, id int) uintptr {
	r, _, _ := procCreateWindowExW.Call(uintptr(ex), uintptr(unsafe.Pointer(u16(class))), uintptr(unsafe.Pointer(u16(text))), uintptr(style), 0, 0, 10, 10, hwndMain, uintptr(id), 0, 0)
	if r != 0 {
		controlsByID[id] = r
		if f := fontForID(id); f != 0 {
			procSendMessageW.Call(r, WM_SETFONT, f, 1)
		}
		if id != ID_COMBO && id != ID_OUTPUT {
			setDarkTheme(r)
		}
	}
	return r
}
func addButton(text string, id int) uintptr {
	return create("BUTTON", text, WS_CHILD|WS_VISIBLE|WS_TABSTOP|BS_OWNERDRAW, 0, id)
}
func addStatic(text string, id int, panel bool) uintptr {
	h := create("STATIC", text, WS_CHILD|WS_VISIBLE|SS_LEFT, 0, id)
	if panel {
		panelStatics[h] = true
	}
	return h
}

var textExtensions = []string{
	".txt", ".md", ".markdown", ".log", ".csv", ".tsv", ".json", ".xml",
	".html", ".htm", ".css", ".js", ".ts", ".py", ".go", ".java", ".kt",
	".c", ".cpp", ".h", ".hpp", ".ini", ".cfg", ".conf", ".yaml", ".yml", ".toml",
}

func regSetString(root uintptr, subkey, name, value string) bool {
	var h uintptr
	sk := u16(subkey)
	r, _, _ := procRegCreateKeyExW.Call(root, uintptr(unsafe.Pointer(sk)), 0, 0, 0, KEY_WRITE, 0, uintptr(unsafe.Pointer(&h)), 0)
	if r != 0 || h == 0 {
		return false
	}
	defer procRegCloseKey.Call(h)
	data := syscall.StringToUTF16(value)
	var namePtr uintptr
	if name != "" {
		n := u16(name)
		namePtr = uintptr(unsafe.Pointer(n))
	}
	r, _, _ = procRegSetValueExW.Call(h, namePtr, 0, REG_SZ, uintptr(unsafe.Pointer(&data[0])), uintptr(len(data)*2))
	return r == 0
}

func registerShellIntegration() bool {
	exe, err := os.Executable()
	if err != nil {
		return false
	}
	exe, _ = filepath.Abs(exe)
	cmd := fmt.Sprintf("\"%s\" \"%%1\"", exe)
	icon := fmt.Sprintf("\"%s\",0", exe)
	ok := true
	set := func(k, n, v string) {
		if !regSetString(HKEY_CURRENT_USER, k, n, v) {
			ok = false
		}
	}

	set(`Software\Microsoft\Windows\CurrentVersion\App Paths\Kunta.exe`, "", exe)
	app := `Software\Classes\Applications\Kunta.exe`
	set(app, "FriendlyAppName", "Kunta")
	set(app+`\DefaultIcon`, "", icon)
	set(app+`\shell\open\command`, "", cmd)
	for _, ext := range textExtensions {
		set(app+`\SupportedTypes`, ext, "")
	}

	// Verbo diretto per i file percepiti come testo.
	base := `Software\Classes\SystemFileAssociations\text\shell\Kunta`
	set(base, "MUIVerb", "Apri in Kunta")
	set(base, "Icon", icon)
	set(base+`\command`, "", cmd)

	// Alcune estensioni non dichiarano PerceivedType=text: registrale senza cambiare l'app predefinita.
	for _, ext := range textExtensions {
		b := `Software\Classes\SystemFileAssociations\` + ext + `\shell\Kunta`
		set(b, "MUIVerb", "Apri in Kunta")
		set(b, "Icon", icon)
		set(b+`\command`, "", cmd)
	}
	procSHChangeNotify.Call(SHCNE_ASSOCCHANGED, 0, 0, 0)
	return ok
}

func unregisterShellIntegration() {
	keys := []string{
		`Software\Classes\SystemFileAssociations\text\shell\Kunta`,
		`Software\Classes\Applications\Kunta.exe`,
		`Software\Microsoft\Windows\CurrentVersion\App Paths\Kunta.exe`,
	}
	for _, ext := range textExtensions {
		keys = append(keys, `Software\Classes\SystemFileAssociations\`+ext+`\shell\Kunta`)
	}
	for _, k := range keys {
		p := u16(k)
		procRegDeleteTreeW.Call(HKEY_CURRENT_USER, uintptr(unsafe.Pointer(p)))
	}
	procSHChangeNotify.Call(SHCNE_ASSOCCHANGED, 0, 0, 0)
}

func safeUI(label string, fn func()) {
	defer func() {
		if r := recover(); r != nil {
			setBusy(false)
			message(fmt.Sprintf("%s: errore interno intercettato.\n%v", label, r))
		}
	}()
	fn()
}

func decodeTextBytes(b []byte) string {
	if len(b) >= 3 && b[0] == 0xEF && b[1] == 0xBB && b[2] == 0xBF {
		return string(b[3:])
	}
	if len(b) >= 2 && ((b[0] == 0xFF && b[1] == 0xFE) || (b[0] == 0xFE && b[1] == 0xFF)) {
		le := b[0] == 0xFF
		b = b[2:]
		u := make([]uint16, 0, len(b)/2)
		for i := 0; i+1 < len(b); i += 2 {
			if le {
				u = append(u, binary.LittleEndian.Uint16(b[i:i+2]))
			} else {
				u = append(u, binary.BigEndian.Uint16(b[i:i+2]))
			}
		}
		return string(utf16.Decode(u))
	}
	return strings.ToValidUTF8(string(b), "�")
}
func loadTextPath(path string) {
	b, err := os.ReadFile(path)
	if err != nil {
		message("Impossibile leggere il file.")
		return
	}
	setText(hInput, decodeTextBytes(b))
	setText(hStatus, fmt.Sprintf("Testo caricato · %.1f KB", float64(len(b))/1024.0))
	procSetFocus.Call(hInput)
}
func hresultFailed(hr uintptr) bool { return int32(uint32(hr)) < 0 }
func comCall(obj uintptr, method int, args ...uintptr) uintptr {
	if obj == 0 {
		return uintptr(0x80004003)
	}
	vtbl := *(*uintptr)(unsafe.Pointer(obj))
	fn := *(*uintptr)(unsafe.Pointer(vtbl + uintptr(method)*unsafe.Sizeof(uintptr(0))))
	callArgs := make([]uintptr, 0, len(args)+1)
	callArgs = append(callArgs, obj)
	callArgs = append(callArgs, args...)
	r, _, _ := syscall.SyscallN(fn, callArgs...)
	return r
}
func utf16PtrToString(p uintptr) string {
	if p == 0 {
		return ""
	}
	a := (*[1 << 28]uint16)(unsafe.Pointer(p))
	n := 0
	for n < len(a) && a[n] != 0 {
		n++
	}
	return syscall.UTF16ToString(a[:n])
}
func openTextFile() {
	var dlg uintptr
	hr, _, _ := procCoCreateInstance.Call(
		uintptr(unsafe.Pointer(&clsidFileOpenDialog)),
		0,
		1, // CLSCTX_INPROC_SERVER
		uintptr(unsafe.Pointer(&iidIFileOpenDialog)),
		uintptr(unsafe.Pointer(&dlg)),
	)
	if hresultFailed(hr) || dlg == 0 {
		message(fmt.Sprintf("Impossibile aprire il selettore file.\nHRESULT: 0x%08X", uint32(hr)))
		return
	}
	defer comCall(dlg, 2) // IUnknown::Release

	n1, s1 := syscall.StringToUTF16("Testi"), syscall.StringToUTF16("*.txt;*.md;*.log;*.csv;*.tsv")
	n2, s2 := syscall.StringToUTF16("Tutti i file"), syscall.StringToUTF16("*.*")
	filters := []COMDLG_FILTERSPEC{{&n1[0], &s1[0]}, {&n2[0], &s2[0]}}
	comCall(dlg, 4, uintptr(len(filters)), uintptr(unsafe.Pointer(&filters[0]))) // SetFileTypes
	comCall(dlg, 9, uintptr(0x40|0x800|0x1000))                                  // FOS_FORCEFILESYSTEM | PATHMUSTEXIST | FILEMUSTEXIST
	title := syscall.StringToUTF16("Apri testo in Kunta")
	comCall(dlg, 17, uintptr(unsafe.Pointer(&title[0]))) // SetTitle

	hr = comCall(dlg, 3, hwndMain) // IModalWindow::Show
	if hresultFailed(hr) {
		// 0x800704C7 = annullato dall'utente: non è un errore.
		if uint32(hr) != 0x800704C7 {
			message(fmt.Sprintf("Il selettore file non si è aperto.\nHRESULT: 0x%08X", uint32(hr)))
		}
		return
	}

	var item uintptr
	hr = comCall(dlg, 20, uintptr(unsafe.Pointer(&item))) // IFileDialog::GetResult
	if hresultFailed(hr) || item == 0 {
		return
	}
	defer comCall(item, 2)

	var pathPtr uintptr
	hr = comCall(item, 5, uintptr(0x80058000), uintptr(unsafe.Pointer(&pathPtr))) // IShellItem::GetDisplayName(SIGDN_FILESYSPATH)
	if hresultFailed(hr) || pathPtr == 0 {
		return
	}
	path := utf16PtrToString(pathPtr)
	procCoTaskMemFree.Call(pathPtr)
	if path != "" {
		loadTextPath(path)
	}
}
func handleDrop(hDrop uintptr) {
	n, _, _ := procDragQueryFileW.Call(hDrop, 0xFFFFFFFF, 0, 0)
	if n > 0 {
		ln, _, _ := procDragQueryFileW.Call(hDrop, 0, 0, 0)
		buf := make([]uint16, int(ln)+1)
		procDragQueryFileW.Call(hDrop, 0, uintptr(unsafe.Pointer(&buf[0])), ln+1)
		loadTextPath(syscall.UTF16ToString(buf))
	}
	procDragFinish.Call(hDrop)
}
func updateHint() {
	if selectedOp >= 0 && selectedOp < len(operations) {
		setText(hHint, operations[selectedOp].Hint)
	}
}
func selectOperation(i int) {
	if i < 0 || i >= len(operations) {
		return
	}
	selectedOp = i
	setText(hCombo, operations[i].Name)
	if hOpList != 0 {
		procSendMessageW.Call(hOpList, LB_SETCURSEL, uintptr(i), 0)
	}
	updateHint()
	procInvalidateRect.Call(hCombo, 0, 1)
}
func showOperationList(show bool) {
	if hOpList == 0 {
		return
	}
	opListOpen = show
	if show {
		procSendMessageW.Call(hOpList, LB_SETCURSEL, uintptr(selectedOp), 0)
		procShowWindow.Call(hOpList, SW_SHOW)
		procSetFocus.Call(hOpList)
	} else {
		procShowWindow.Call(hOpList, SW_HIDE)
	}
	procInvalidateRect.Call(hCombo, 0, 1)
}
func setBusy(v bool) {
	busyMu.Lock()
	busy = v
	busyMu.Unlock()
	ids := []int{ID_RUN, ID_QUICK_AZ, ID_QUICK_REP, ID_QUICK_KUNTA, ID_QUICK_VOW, ID_QUICK_CONS}
	enabled := uintptr(1)
	if v {
		enabled = 0
	}
	for _, id := range ids {
		procEnableWindow.Call(controlsByID[id], enabled)
	}
	procEnableWindow.Call(hCombo, enabled)
	procEnableWindow.Call(hOpList, enabled)
	if v {
		showOperationList(false)
		setText(hStatus, "Kunta sta lavorando…")
	} else {
		setText(hStatus, fmt.Sprintf("Locale · %d operazioni · menu destro attivo · nessun invio esterno", len(operations)))
	}
}
func runOp(op int) {
	busyMu.Lock()
	already := busy
	busyMu.Unlock()
	if already {
		return
	}
	txt := textOf(hInput)
	if txt == "" {
		replaceOutput("Non c’è testo da analizzare.")
		return
	}
	param := textOf(hParam)
	checked, _, _ := procSendMessageW.Call(hCase, BM_GETCHECK, 0, 0)
	sensitive := checked == BST_CHECKED
	replaceOutput("")
	setBusy(true)
	go func() {
		res := ""
		defer func() {
			if r := recover(); r != nil {
				res = fmt.Sprintf("Errore interno durante l’analisi: %v", r)
			}
			resultMu.Lock()
			pendingResult = res
			resultMu.Unlock()
			procPostMessageW.Call(hwndMain, WM_APP_ANALYSIS_DONE, 0, 0)
		}()
		res = analyze(txt, op, param, sensitive)
	}()
}

func layout() {
	var r RECT
	procGetClientRect.Call(hwndMain, uintptr(unsafe.Pointer(&r)))
	w, h := int(r.Right-r.Left), int(r.Bottom-r.Top)
	pad, gap := scale(14), scale(9)
	if w < scale(820) {
		w = scale(820)
	}
	if h < scale(680) {
		h = scale(680)
	}

	y := scale(13)
	iconW := scale(50)
	move(hTitle, pad+iconW+scale(10), y+scale(2), scale(320), scale(31))
	move(hTagline, pad+iconW+scale(10), y+scale(31), scale(440), scale(20))
	y += scale(62)

	btnH := scale(40)
	move(controlsByID[ID_PASTE], pad, y, scale(105), btnH)
	move(controlsByID[ID_OPEN], pad+scale(114), y, scale(138), btnH)
	move(controlsByID[ID_CLEAR], pad+scale(261), y, scale(105), btnH)
	y += btnH + gap

	bottomReserve := scale(385)
	inputH := (h - y - bottomReserve) * 46 / 100
	if inputH < scale(135) {
		inputH = scale(135)
	}
	move(hInput, pad, y, w-2*pad, inputH)
	y += inputH + gap

	quickW := (w - 2*pad - 4*gap) / 5
	qs := []int{ID_QUICK_AZ, ID_QUICK_REP, ID_QUICK_KUNTA, ID_QUICK_VOW, ID_QUICK_CONS}
	x := pad
	for _, id := range qs {
		move(controlsByID[id], x, y, quickW, btnH)
		x += quickW + gap
	}
	y += btnH + gap

	panelX, panelY := pad, y
	panelW, panelH := w-2*pad, scale(112)
	controlPanel = RECT{int32(panelX), int32(panelY), int32(panelX + panelW), int32(panelY + panelH)}
	inner := scale(10)
	labelH := scale(18)
	comboW := panelW * 46 / 100
	paramW := panelW * 18 / 100
	rightX := panelX + comboW + paramW + 2*gap
	rightW := panelX + panelW - inner - rightX

	move(controlsByID[ID_LABEL_OPERATION], panelX+inner, panelY+scale(8), comboW-inner*2, labelH)
	move(controlsByID[ID_LABEL_PARAM], panelX+comboW+gap+inner, panelY+scale(8), paramW-inner*2, labelH)
	fieldY := panelY + scale(31)
	move(hCombo, panelX+inner, fieldY, comboW-inner*2, scale(36))
	listH := scale(420)
	maxListH := h - (fieldY + scale(38)) - scale(68)
	if maxListH < scale(150) {
		maxListH = scale(150)
	}
	if listH > maxListH {
		listH = maxListH
	}
	move(hOpList, panelX+inner, fieldY+scale(37), comboW-inner*2, listH)
	move(hParam, panelX+comboW+gap+inner, fieldY, paramW-inner*2, scale(36))
	runW := scale(105)
	caseW := rightW - runW - gap
	if caseW < scale(190) {
		caseW = scale(190)
	}
	move(hCase, rightX, fieldY, caseW, scale(36))
	move(controlsByID[ID_RUN], panelX+panelW-inner-runW, fieldY, runW, scale(36))
	move(hHint, panelX+inner, panelY+scale(75), panelW-inner*2, scale(25))

	y = panelY + panelH + gap
	footerH := scale(54)
	outH := h - y - footerH - pad
	if outH < scale(125) {
		outH = scale(125)
	}
	move(hOutput, pad, y, w-2*pad, outH)
	y += outH + gap
	move(controlsByID[ID_COPY], pad, y, scale(155), scale(36))
	footerW := scale(165)
	footerX := w - pad - footerW
	statusX := pad + scale(169)
	statusW := footerX - statusX - gap
	if statusW < scale(120) {
		statusW = scale(120)
	}
	move(hStatus, statusX, y+scale(8), statusW, scale(24))
	move(hFooter, footerX, y, footerW, scale(50))
	procInvalidateRect.Call(hwndMain, 0, 0)
}

func buttonStyle(id uint32) (bg, fg uintptr) {
	switch id {
	case ID_RUN:
		return colAccent, colAccentInk
	case ID_QUICK_AZ, ID_QUICK_REP, ID_QUICK_KUNTA, ID_QUICK_VOW, ID_QUICK_CONS:
		return colSoft, colText
	default:
		return colPanel, colText
	}
}
func drawRoundedBox(hdc uintptr, rc RECT, bg, border uintptr, radius int) {
	b, _, _ := procCreateSolidBrush.Call(bg)
	p, _, _ := procCreatePen.Call(PS_SOLID, 1, border)
	oldB, _, _ := procSelectObject.Call(hdc, b)
	oldP, _, _ := procSelectObject.Call(hdc, p)
	procRoundRect.Call(hdc, uintptr(rc.Left), uintptr(rc.Top), uintptr(rc.Right), uintptr(rc.Bottom), uintptr(radius), uintptr(radius))
	procSelectObject.Call(hdc, oldB)
	procSelectObject.Call(hdc, oldP)
	procDeleteObject.Call(b)
	procDeleteObject.Call(p)
}
func drawBotoloAt(hdc uintptr, x, y, dw, dh int) {
	if len(botoloPixels) == 0 || botoloWidth <= 0 || botoloHeight <= 0 {
		return
	}
	bmi := BITMAPINFO{Header: BITMAPINFOHEADER{
		Size: uint32(unsafe.Sizeof(BITMAPINFOHEADER{})), Width: int32(botoloWidth), Height: int32(botoloHeight),
		Planes: 1, BitCount: 24, Compression: 0, SizeImage: uint32(botoloStride * botoloHeight),
	}}
	procStretchDIBits.Call(hdc, uintptr(x), uintptr(y), uintptr(dw), uintptr(dh), 0, 0,
		uintptr(botoloWidth), uintptr(botoloHeight), uintptr(unsafe.Pointer(&botoloPixels[0])), uintptr(unsafe.Pointer(&bmi)), 0, 0x00CC0020)
}

func drawOwnerButton(di *DRAWITEMSTRUCT) {
	if di.CtlID == ID_COMBO {
		bg := colInput
		drawRoundedBox(di.HDC, di.RcItem, bg, colLine, scale(4))
		procSetBkMode.Call(di.HDC, TRANSPARENT)
		procSetTextColor.Call(di.HDC, colText)
		rr := di.RcItem
		rr.Left += int32(scale(10))
		rr.Right -= int32(scale(36))
		procDrawTextW.Call(di.HDC, uintptr(unsafe.Pointer(u16(textOf(di.HwndItem)))), ^uintptr(0), uintptr(unsafe.Pointer(&rr)), DT_LEFT|DT_VCENTER|DT_SINGLELINE|DT_END_ELLIPSIS)
		ar := di.RcItem
		ar.Left = ar.Right - int32(scale(32))
		procDrawTextW.Call(di.HDC, uintptr(unsafe.Pointer(u16("▾"))), ^uintptr(0), uintptr(unsafe.Pointer(&ar)), DT_CENTER|DT_VCENTER|DT_SINGLELINE)
		return
	}
	if di.CtlID == ID_FOOTER {
		bg := colBG
		b, _, _ := procCreateSolidBrush.Call(bg)
		procFillRect.Call(di.HDC, uintptr(unsafe.Pointer(&di.RcItem)), b)
		procDeleteObject.Call(b)

		icon := scale(50)
		textW := scale(78)
		gap := scale(7)
		right := int(di.RcItem.Right) - scale(2)
		x := right - textW - gap - icon
		y := int(di.RcItem.Bottom) - icon
		drawBotoloAt(di.HDC, x, y, icon, icon)

		procSetBkMode.Call(di.HDC, TRANSPARENT)
		nameR := di.RcItem
		nameR.Left = int32(x + icon + gap)
		nameR.Right = int32(right)
		nameR.Top = int32(y)
		nameR.Bottom = int32(y + icon)
		oldFont, _, _ := procSelectObject.Call(di.HDC, fontBold)
		procSetTextColor.Call(di.HDC, colText)
		procDrawTextW.Call(di.HDC, uintptr(unsafe.Pointer(u16("ShiduLab"))), ^uintptr(0), uintptr(unsafe.Pointer(&nameR)), DT_LEFT|DT_BOTTOM|DT_SINGLELINE)
		if oldFont != 0 {
			procSelectObject.Call(di.HDC, oldFont)
		}
		return
	}
	bg, fg := buttonStyle(di.CtlID)
	if di.ItemState&ODS_SELECTED != 0 {
		if di.CtlID == ID_RUN {
			bg = rgb(103, 160, 37)
		} else {
			bg = rgb(43, 53, 40)
		}
	}
	drawRoundedBox(di.HDC, di.RcItem, bg, colLine, scale(7))
	procSetBkMode.Call(di.HDC, TRANSPARENT)
	procSetTextColor.Call(di.HDC, fg)
	txt := textOf(di.HwndItem)
	rr := di.RcItem
	procDrawTextW.Call(di.HDC, uintptr(unsafe.Pointer(u16(txt))), ^uintptr(0), uintptr(unsafe.Pointer(&rr)), DT_CENTER|DT_VCENTER|DT_SINGLELINE|DT_END_ELLIPSIS)
}
func comboItemText(hwnd uintptr, itemID uint32) string {
	if itemID == 0xFFFFFFFF {
		i, _, _ := procSendMessageW.Call(hwnd, CB_GETCURSEL, 0, 0)
		if int(i) < 0 {
			return ""
		}
		itemID = uint32(i)
	}
	ln, _, _ := procSendMessageW.Call(hwnd, CB_GETLBTEXTLEN, uintptr(itemID), 0)
	if int32(ln) < 0 {
		return ""
	}
	buf := make([]uint16, int(ln)+1)
	procSendMessageW.Call(hwnd, CB_GETLBTEXT, uintptr(itemID), uintptr(unsafe.Pointer(&buf[0])))
	return syscall.UTF16ToString(buf)
}
func drawOwnerCombo(di *DRAWITEMSTRUCT) {
	bg := colPanel
	if di.ItemState&ODS_SELECTED != 0 {
		bg = colSoft
	}
	b, _, _ := procCreateSolidBrush.Call(bg)
	procFillRect.Call(di.HDC, uintptr(unsafe.Pointer(&di.RcItem)), b)
	procDeleteObject.Call(b)
	procSetBkMode.Call(di.HDC, TRANSPARENT)
	procSetTextColor.Call(di.HDC, colText)
	rr := di.RcItem
	rr.Left += int32(scale(9))
	rr.Right -= int32(scale(6))
	txt := comboItemText(di.HwndItem, di.ItemID)
	procDrawTextW.Call(di.HDC, uintptr(unsafe.Pointer(u16(txt))), ^uintptr(0), uintptr(unsafe.Pointer(&rr)), DT_LEFT|DT_VCENTER|DT_SINGLELINE|DT_END_ELLIPSIS)
}
func initBotolo() {
	if len(botoloBMP) < 54 || string(botoloBMP[:2]) != "BM" {
		return
	}
	off := int(binary.LittleEndian.Uint32(botoloBMP[10:14]))
	w := int(int32(binary.LittleEndian.Uint32(botoloBMP[18:22])))
	h := int(int32(binary.LittleEndian.Uint32(botoloBMP[22:26])))
	bpp := int(binary.LittleEndian.Uint16(botoloBMP[28:30]))
	if off <= 0 || w <= 0 || h == 0 || bpp != 24 {
		return
	}
	if h < 0 {
		h = -h
	}
	stride := ((w*3 + 3) / 4) * 4
	need := off + stride*h
	if need > len(botoloBMP) {
		return
	}
	pix := append([]byte(nil), botoloBMP[off:need]...)
	botoloPixels, botoloWidth, botoloHeight, botoloStride = pix, w, h, stride
}

func paintBackground(hwnd uintptr) {
	var ps PAINTSTRUCT
	hdc, _, _ := procBeginPaint.Call(hwnd, uintptr(unsafe.Pointer(&ps)))
	if hdc != 0 {
		var r RECT
		procGetClientRect.Call(hwnd, uintptr(unsafe.Pointer(&r)))
		procFillRect.Call(hdc, uintptr(unsafe.Pointer(&r)), brushBG)
		if controlPanel.Right > controlPanel.Left {
			drawRoundedBox(hdc, controlPanel, colPanel, colLine, scale(9))
		}
		if appIcon != 0 {
			procDrawIconEx.Call(hdc, uintptr(scale(14)), uintptr(scale(14)), appIcon, uintptr(scale(48)), uintptr(scale(48)), 0, 0, DI_NORMAL)
		}
	}
	procEndPaint.Call(hwnd, uintptr(unsafe.Pointer(&ps)))
}
func applyDPI(hwnd uintptr) {
	if dpi, _, _ := procGetDpiForWindow.Call(hwnd); dpi >= 72 && dpi <= 384 {
		currentDPI = int(dpi)
	}
}
func setControlFonts() {
	h := func(px int, weight int, face string) uintptr {
		height := -scale(px)
		r, _, _ := procCreateFontW.Call(uintptr(int64(height)), 0, 0, 0, uintptr(weight), 0, 0, 0, 1, 0, 0, 5, 0, uintptr(unsafe.Pointer(u16(face))))
		return r
	}
	fontUI = h(17, 400, "Segoe UI")
	fontSmall = h(14, 400, "Segoe UI")
	fontTitle = h(27, 600, "Segoe UI")
	fontMono = h(15, 400, "Consolas")
	fontBold = h(17, 700, "Segoe UI")
}

func wndProc(hwnd uintptr, msg uint32, wParam, lParam uintptr) uintptr {
	switch msg {
	case WM_DESTROY:
		procPostQuitMessage.Call(0)
		return 0
	case WM_ERASEBKGND:
		return 1
	case WM_GETMINMAXINFO:
		if lParam != 0 {
			m := (*MINMAXINFO)(unsafe.Pointer(lParam))
			m.PtMinTrackSize.X = int32(scale(820))
			m.PtMinTrackSize.Y = int32(scale(680))
			return 0
		}
	case WM_SIZE:
		layout()
		return 0
	case WM_PAINT:
		paintBackground(hwnd)
		return 0
	case WM_DROPFILES:
		handleDrop(wParam)
		return 0
	case WM_DRAWITEM:
		if lParam != 0 {
			di := (*DRAWITEMSTRUCT)(unsafe.Pointer(lParam))
			if di.CtlType == ODT_BUTTON {
				drawOwnerButton(di)
				return 1
			}
		}
	case WM_CTLCOLOREDIT:
		hdc := wParam
		procSetTextColor.Call(hdc, colText)
		procSetBkColor.Call(hdc, colInput)
		return brushInput
	case WM_CTLCOLORLISTBOX:
		hdc := wParam
		procSetTextColor.Call(hdc, colText)
		procSetBkColor.Call(hdc, colPanel)
		return brushPanel
	case WM_CTLCOLORSTATIC:
		hdc := wParam
		ctl := lParam
		if ctl == hOutput {
			procSetBkMode.Call(hdc, OPAQUE)
			procSetTextColor.Call(hdc, colText)
			procSetBkColor.Call(hdc, colInput)
			return brushInput
		}
		procSetBkMode.Call(hdc, TRANSPARENT)
		if ctl == hTitle {
			procSetTextColor.Call(hdc, colText)
		} else {
			procSetTextColor.Call(hdc, colMuted)
		}
		if panelStatics[ctl] {
			return brushPanel
		}
		return brushBG
	case WM_CTLCOLORBTN:
		hdc := wParam
		procSetTextColor.Call(hdc, colText)
		procSetBkColor.Call(hdc, colPanel)
		return brushPanel
	case WM_APP_ANALYSIS_DONE:
		resultMu.Lock()
		res := pendingResult
		pendingResult = ""
		resultMu.Unlock()
		replaceOutput(res)
		setBusy(false)
		return 0
	case WM_COMMAND:
		id := int(wParam & 0xffff)
		code := int((wParam >> 16) & 0xffff)
		switch id {
		case ID_PASTE:
			if code != 0 {
				return 0
			} // BN_CLICKED
			procSetFocus.Call(hInput)
			procSendMessageW.Call(hInput, WM_PASTE, 0, 0)
		case ID_OPEN:
			if code != 0 {
				return 0
			} // BN_CLICKED
			safeUI("Apri testo", openTextFile)
		case ID_CLEAR:
			if code != 0 {
				return 0
			} // BN_CLICKED
			setText(hInput, "")
			replaceOutput("")
			setText(hParam, "")
			setText(hStatus, fmt.Sprintf("Locale · %d operazioni · menu destro attivo · nessun invio esterno", len(operations)))
			procSetFocus.Call(hInput)
		case ID_QUICK_AZ:
			if code != 0 {
				return 0
			} // BN_CLICKED
			selectOperation(20)
			safeUI("A–Z", func() { runOp(20) })
		case ID_QUICK_REP:
			if code != 0 {
				return 0
			} // BN_CLICKED
			selectOperation(9)
			safeUI("Ripetizioni", func() { runOp(9) })
		case ID_QUICK_KUNTA:
			if code != 0 {
				return 0
			} // BN_CLICKED
			selectOperation(26)
			safeUI("Kunta il testo", func() { runOp(26) })
		case ID_QUICK_VOW:
			if code != 0 {
				return 0
			} // BN_CLICKED
			selectOperation(27)
			safeUI("Isovocaliche", func() { runOp(27) })
		case ID_QUICK_CONS:
			if code != 0 {
				return 0
			} // BN_CLICKED
			selectOperation(28)
			safeUI("Isoconsonantiche", func() { runOp(28) })
		case ID_COMBO:
			if code == 0 { // BN_CLICKED
				showOperationList(!opListOpen)
			}
		case ID_OPLIST:
			if code == 1 { // LBN_SELCHANGE
				i, _, _ := procSendMessageW.Call(hOpList, LB_GETCURSEL, 0, 0)
				if int(i) >= 0 && int(i) < len(operations) {
					selectOperation(int(i))
				}
				showOperationList(false)
				procSetFocus.Call(hCombo)
			}
		case ID_RUN:
			if code != 0 {
				return 0
			} // BN_CLICKED
			showOperationList(false)
			safeUI("KUNTA", func() { runOp(selectedOp) })
		case ID_COPY:
			if code != 0 {
				return 0
			} // BN_CLICKED
			procSendMessageW.Call(hOutput, EM_SETSEL, 0, ^uintptr(0))
			procSendMessageW.Call(hOutput, WM_COPY, 0, 0)
			setText(hStatus, "Risultato copiato.")
		case ID_FOOTER:
			if code != 0 {
				return 0
			}
			procShellExecuteW.Call(hwndMain,
				uintptr(unsafe.Pointer(u16("open"))),
				uintptr(unsafe.Pointer(u16(repoURL))),
				0, 0, 1)
		}
		return 0
	}
	r, _, _ := procDefWindowProcW.Call(hwnd, uintptr(msg), wParam, lParam)
	return r
}

func main() {
	runtime.LockOSThread()
	// Per-monitor DPI awareness: dimensioni coerenti con scala e risoluzione del monitor.
	procSetProcessDpiAwarenessContext.Call(^uintptr(3))

	if len(os.Args) > 1 && os.Args[1] == "--remove-context-menu" {
		unregisterShellIntegration()
		return
	}
	contextOK := registerShellIntegration()
	startupFile := ""
	for _, arg := range os.Args[1:] {
		if strings.HasPrefix(arg, "--") {
			continue
		}
		if fi, err := os.Stat(arg); err == nil && !fi.IsDir() {
			startupFile = arg
			break
		}
	}
	hrCOM, _, _ := procCoInitializeEx.Call(0, 0x2) // COINIT_APARTMENTTHREADED
	if !hresultFailed(hrCOM) {
		defer procCoUninitialize.Call()
	}
	initBotolo()
	hInst, _, _ := procGetModuleHandleW.Call(0)
	cur, _, _ := procLoadCursorW.Call(0, 32512)
	appIcon, _, _ = procLoadIconW.Call(hInst, 1)

	brushBG, _, _ = procCreateSolidBrush.Call(colBG)
	brushPanel, _, _ = procCreateSolidBrush.Call(colPanel)
	brushInput, _, _ = procCreateSolidBrush.Call(colInput)
	brushAccent, _, _ = procCreateSolidBrush.Call(colAccent)
	brushSoft, _, _ = procCreateSolidBrush.Call(colSoft)
	brushLine, _, _ = procCreateSolidBrush.Call(colLine)

	class := u16("KuntaNativeWindowFinal")
	wc := WNDCLASSEX{CbSize: uint32(unsafe.Sizeof(WNDCLASSEX{})), LpfnWndProc: syscall.NewCallback(wndProc), HInstance: hInst, HIcon: appIcon, HCursor: cur, HbrBackground: brushBG, LpszClassName: class, HIconSm: appIcon}
	if r, _, _ := procRegisterClassExW.Call(uintptr(unsafe.Pointer(&wc))); r == 0 {
		return
	}

	hwndMain, _, _ = procCreateWindowExW.Call(0, uintptr(unsafe.Pointer(class)), uintptr(unsafe.Pointer(u16("Kunta"))), WS_OVERLAPPEDWINDOW|WS_CLIPCHILDREN, CW_USEDEFAULT, CW_USEDEFAULT, 1120, 860, 0, 0, hInst, 0)
	if hwndMain == 0 {
		return
	}
	applyDPI(hwndMain)
	setImmersiveDarkTitlebar(hwndMain)
	setControlFonts()
	procDragAcceptFiles.Call(hwndMain, 1)

	hTitle = addStatic("Kunta", ID_TITLE, false)
	hTagline = addStatic("Conta · osserva · ordina · rac-conta", ID_TAGLINE, false)

	addButton("Incolla", ID_PASTE)
	addButton("Apri testo…", ID_OPEN)
	addButton("Pulisci", ID_CLEAR)

	hInput = create("EDIT", "", WS_CHILD|WS_VISIBLE|WS_TABSTOP|WS_VSCROLL|ES_MULTILINE|ES_AUTOVSCROLL|ES_WANTRETURN|ES_NOHIDESEL, WS_EX_CLIENTEDGE, ID_EDIT_INPUT)
	procSendMessageW.Call(hInput, EM_SETMARGINS, EC_LEFTMARGIN|EC_RIGHTMARGIN, uintptr(scale(10)|(scale(10)<<16)))
	procSendMessageW.Call(hInput, EM_SETLIMITTEXT, 0x7FFFFFFE, 0)

	addButton("A–Z", ID_QUICK_AZ)
	addButton("Ripetizioni", ID_QUICK_REP)
	addButton("Kunta il testo", ID_QUICK_KUNTA)
	addButton("Isovocaliche", ID_QUICK_VOW)
	addButton("Isoconsonantiche", ID_QUICK_CONS)

	addStatic(fmt.Sprintf("Operazione · %d voci", len(operations)), ID_LABEL_OPERATION, true)
	addStatic("Parametro", ID_LABEL_PARAM, true)
	hCombo = addButton("", ID_COMBO)

	hParam = create("EDIT", "", WS_CHILD|WS_VISIBLE|WS_TABSTOP|ES_AUTOHSCROLL, WS_EX_CLIENTEDGE, ID_PARAM)
	procSendMessageW.Call(hParam, EM_SETMARGINS, EC_LEFTMARGIN|EC_RIGHTMARGIN, uintptr(scale(8)|(scale(8)<<16)))
	hCase = create("BUTTON", "Maiuscole/minuscole distinte", WS_CHILD|WS_VISIBLE|WS_TABSTOP|BS_AUTOCHECKBOX, 0, ID_CASE)
	addButton("KUNTA!", ID_RUN)
	hHint = addStatic("", ID_HINT, true)
	updateHint()

	hOutput = create("EDIT", "", WS_CHILD|WS_VISIBLE|WS_VSCROLL|ES_MULTILINE|ES_AUTOVSCROLL|ES_WANTRETURN|ES_READONLY|ES_NOHIDESEL, WS_EX_CLIENTEDGE, ID_OUTPUT)
	procSendMessageW.Call(hOutput, EM_SETMARGINS, EC_LEFTMARGIN|EC_RIGHTMARGIN, uintptr(scale(10)|(scale(10)<<16)))
	procSendMessageW.Call(hOutput, EM_SETLIMITTEXT, 0x7FFFFFFE, 0)
	addButton("Copia risultato", ID_COPY)
	statusText := fmt.Sprintf("Locale · %d operazioni · nessun invio esterno", len(operations))
	if contextOK {
		statusText = fmt.Sprintf("Locale · %d operazioni · menu destro attivo · nessun invio esterno", len(operations))
	}
	hStatus = addStatic(statusText, ID_STATUS, false)
	hFooter = addButton("ShiduLab", ID_FOOTER)

	// Creato per ultimo: quando aperto resta sopra agli altri controlli, come una vera tendina.
	hOpList = create("LISTBOX", "", WS_CHILD|WS_TABSTOP|WS_VSCROLL|LBS_NOTIFY|LBS_NOINTEGRALHEIGHT, WS_EX_CLIENTEDGE, ID_OPLIST)
	for _, op := range operations {
		procSendMessageW.Call(hOpList, LB_ADDSTRING, 0, uintptr(unsafe.Pointer(u16(op.Name))))
	}
	if n, _, _ := procSendMessageW.Call(hOpList, LB_GETCOUNT, 0, 0); int(n) != len(operations) {
		message(fmt.Sprintf("Errore interno: operazioni caricate %d su %d.", int(n), len(operations)))
	}
	selectOperation(20)
	showOperationList(false)

	layout()
	procShowWindow.Call(hwndMain, SW_MAXIMIZE)
	procInvalidateRect.Call(hwndMain, 0, 1)
	if startupFile != "" {
		safeUI("Apertura da Esplora file", func() { loadTextPath(startupFile) })
	} else {
		procSetFocus.Call(hInput)
	}

	var msg MSG
	for {
		r, _, _ := procGetMessageW.Call(uintptr(unsafe.Pointer(&msg)), 0, 0, 0)
		if int32(r) <= 0 {
			break
		}
		procTranslateMessage.Call(uintptr(unsafe.Pointer(&msg)))
		procDispatchMessageW.Call(uintptr(unsafe.Pointer(&msg)))
	}
}
